EnergySage/es-ds

- Makefile
- README.md
- es-design-system/package-lock.json
- es-vue-base/README.md
- es-vue-base/package-lock.json
- es-vue-base/package.json
- package.json
- Running `npm --prefix es-vue-base run build` without building `es-bs-base` first causes an error.
- `es-vue-base` references the `es-bs-base` package via a node_modules alias (`~`), so `es-bs-base` must be built prior to building `es-vue-base`.
- Building also fails in `es-vue-base` if peer dependencies are not installed prior as well.
- Added `build-scss-pkg` and `update-peer-deps` *Makefile* commands
- Removed *make install*
- Added documentation in around initial `es-ds` set-up in a section called "Installing Dependencies and Linking packages"
> Remove "make install" and codify how to install es-ds from scratch

- es-vue-base/src/lib-components/EsFormInput.vue
Was getting:
```
[Vue warn]: Invalid prop: custom validator check failed for prop "type".
```
When adding the form-input to the login vertical. Login form requires `input[type=password]` and `input[type=email]`
- Add `email`, `number`, `password`
> Add additional input types to the form-input component

- es-design-system/pages/molecules/es-popover.vue
- es-vue-base/src/lib-components/EsPopover.vue
- es-vue-base/tests/EsPopover.spec.js
ESDS-69 Popover Color Schemes
- https://energysage.atlassian.net/browse/ESDS-69
- Added `customClass` prop to `EsPopover`
- Created custom classes for each color scheme (`es-popover-light` and `es-popover-dark`)
- Visual
- The design for the "light" popover in Figma had a gradient as the border color. From what I've read, it's not possible to set a gradient for anything other than `background` in css. I've used `$primary` instead for now. Is there a workaround to use the gradient, or should I ask for approval of a solid color from design?
- Change the default value of `customClass` in `EsPopover` to view the different color schemes. 
- Change the default value of `placement` to make sure there are no regressions with the arrow/arrow border
> ESDS-69 Popover Color Schemes

- es-bs-base/scss/_variables.scss
- es-bs-base/scss/utilities/_text.scss
- es-design-system/nuxt.config.js
- es-design-system/pages/atoms/typography.vue
- es-vue-base/src/lib-components/EsFormInput.vue
- es-vue-base/src/lib-components/EsFormTextarea.vue
- es-vue-base/tests/__snapshots__/EsFormTextarea.spec.js.snap
- es-vue-base/tests/__snapshots__/EsForminput.spec.js.snap
- https://energysage.atlassian.net/browse/ESDS-79
- Added `$font-weight-semibold` variable
- Added `font-weight-semibold` utility class
- Switched EsFormInput and EsFormTextarea to use the `font-weight-semibold` utility class on their `<label>` components
- Updated Jest snapshots for EsFormInput and EsFormTextarea
- Added 200 and 300 font weights to the Google Fonts call for the Inter font, since we already have utility classes trying to use those weights
- Added "Font Weight Utility Classes" documentation to the Typography page
- Clicked through the `es-design-system` site in desktop Chrome, Firefox, and Safari
- Overall approach, anything I missed
- `make build` to build `es-bs-base` (where the SCSS changes are) and `es-vue-base` (where the component changes are)
- `make symlink` should …
> ESDS-79 used new font-weight-semibold class for EsFormInput/Textarea

- es-design-system/package.json
- es-design-system/pages/molecules/es-form-input.vue
- es-vue-base/package-lock.json
- es-vue-base/package.json
- es-vue-base/src/lib-components/EsFormInput.vue
- es-vue-base/tests/__snapshots__/EsForminput.spec.js.snap
- Add additional extra-context slot to input fields
Need to add an additional line to the login-page on `accounts.energysage` to point users without a password to the OTP flow. Similar to what's currently live on WWW:
- Manual
- Ok if I merge & deploy this?
> Add extra-context slot

- es-bs-base/scss/_variables.scss
- es-design-system/nuxt.config.js
- es-design-system/pages/atoms/typography.vue
- https://energysage.atlassian.net/browse/ESDS-87
- Updated all headings to be font weight 700 instead of 600, per [the design](https://www.figma.com/file/ILnQorHR2IcGAsIkme9Ctb/ESDS-1.0?node-id=59%3A538)
- Swapped the font weights of `bolder` (used) and `boldest` (not used) so `bolder` is now 700
- Removed unused font weights 800 and 900 from the Google Fonts include and added 700
- Updated the utility class table on the Typography page of the design system site to reflect the new 700 weight for `bolder`
- Loaded design system site in Firefox, Safari, Chrome to ensure font weight rendered properly
- Searched the es-ds codebase thoroughly for all instances of font weight variable use that could be affected
- Viewed all other pages of the design system site to ensure no other components …
> ESDS-87 updated headings and 'bolder' to font weight 700

- es-design-system/pages/organisms/es-form.vue
- es-vue-base/src/lib-mixins/forms.js
- es-vue-base/tests/mixins/forms.spec.js
- Add check to `validateState` in the event a form field doesn't include a `validations` definition.
- Manual tested in browser & automated test
- To validate the fix, add a form field without related `validations` definitions. Without the check, the page will fail to render throwing an exception.
> Check if form field doesn't have a related validations def

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
I think we should depart from ES the issue template used for private ES repos, and instead more towards a more generic process. Happy to have a meeting to discuss this idea further!
> Update issue templates

- es-bs-base/scss/variables/_breakpoints.scss
- es-bs-base/scss/variables/_max-widths.scss
- es-design-system/pages/atoms/layout.vue
https://energysage.atlassian.net/browse/ESDS-106
Since our breakpoints and max widths differ slightly from the [Bootstrap](https://getbootstrap.com/docs/4.0/layout/grid/#grid-options) and [Bootstrap Vue](https://bootstrap-vue.org/docs/components/layout#grid-options) documentation - namely, in that we use an extra `xxl` breakpoint - I've added a Responsive Breakpoints table to the Layout page explaining this. It uses the Sass variables directly, so it will update if we ever change a breakpoint or max width pixel value. This should be useful for both engineers and designers to reference.
Loaded the Layout page in Chrome, Firefox, and Safari.
> docs: added responsive breakpoints table to Layout page

- CHANGELOG.md
- es-bs-base/scss/utilities/_background.scss
- https://energysage.atlassian.net/browse/ESDS-111
- ***BREAKING CHANGE:*** Adds the `!important` keyword back to `bg-{color}` utility classes
- Updates the CHANGELOG to indicate that the v0.12.0 release contained a breaking change that was the removal of the `!important` keyword from the `bg-white` class (see ticket for more details on the regression this introduced).
- Loaded the Colors docs page to ensure the bg colors are rendering properly and inspected the element to ensure the `!important` keyword was present.
> fix: add !important back to bg color utility classes, add breaking change note to v12 changelog

- es-bs-base/scss/_forms.scss
- es-bs-base/scss/utilities/_sizing.scss
- es-design-system/components/ds-examples-list.vue
- es-design-system/pages/examples/form-field-validation.vue
- es-design-system/pages/examples/form-validation.vue
- es-design-system/pages/organisms/es-form.vue
- es-vue-base/src/lib-mixins/forms.js
*More details in inline-comments*
- https://energysage.atlassian.net/wiki/spaces/DS/pages/198311937/2023-01-31+Loading+UI+User+feedback+for+long-running+requests+Upcoming
- Added min-width `em` based utility classes (the spinner can go beyond the width of a button if it's width is auto)
- Added width-auto utility classes (previously this was scoped style in a component example)
- Split form validation into two pages, so each are more focused on a particular feature
- manual (in chrome)
> add utility classes and examples for loading button

- es-vue-base/src/lib-components/EsFormRadioCard.vue
- https://energysage.atlassian.net/browse/ESDS-110
- I found a hover state built out in a design and decided to better match the interactivity of EsButton (from which EsFormRadioCard borrows styles) by implementing the hover state, vs. having none
- Hovered the radio card
> fix: add hover state to EsFormRadioCard

- es-design-system/pages/molecules/es-form-radio-cards.vue
- https://energysage.atlassian.net/browse/ESDS-110
- Radio cards documentation was initially developed before the recent EsButton changes were merged in, so the mobile layout inside the "Custom card styling" example cards was assuming a button display of `block` or `inline-block`. With the new EsButton changes, default display for buttons updated to `inline-flex`, so some of the desktop-targeted flex styles like `flex-column` began applying on mobile unintentionally. This PR explicitly sets mobile display to `block` for the intended layout.
(would display screenshots here but GitHub is currently having an issue uploading images)
- Viewed layout in Chrome responsive devtools on mobile size
> fix: internal layout of mobile radio cards custom styling example

- es-bs-base/scss/_buttons.scss
- es-design-system/pages/molecules/es-button.vue
- https://energysage.atlassian.net/browse/ESDS-123
- Fixed an issue where button content was not centered when the width is larger than the content
- Added an example to the EsButton docs page demonstrating the primary case where this occurs: when the button is full width on mobile but content width on desktop (also makes use of the new `w-lg-auto` utility class added recently)
- Used Chrome responsive devtools to view full width button on mobile and content width button on desktop, tested before and after to see left-aligned content shift to center-aligned content
> fix: button content is now centered by default

- es-design-system/pages/molecules/es-form-input.vue
- es-vue-base/src/lib-components/EsFormInput.vue
- https://energysage.atlassian.net/browse/ESDS-127
- Added a `labelSrOnly` prop to EsFormInput for cases where the form consists of only an input and a submit button within a stylized marketing section like a hero or a CTA banner, and the placeholder text is used as the label for visual users.
- Simplified and broadened the number of examples on the EsFormInput page.
- Tested on docs page in Chrome with responsive devtools
> feat: new labelSrOnly prop for EsFormInput

- es-design-system/pages/molecules/es-button.vue
- es-vue-base/src/lib-components/EsButton.vue
- es-vue-base/src/lib-components/EsCollapse.vue
- es-vue-base/src/lib-components/EsViewMore.vue
- es-vue-base/tests/__snapshots__/EsCollapse.spec.js.snap
- es-vue-base/tests/__snapshots__/EsViewMore.spec.js.snap
- https://energysage.atlassian.net/browse/ESDS-118
- Added an `inline` prop for EsButton, only for use with the `link` variant, that removes the padding, height, border, etc. to make it align perfectly with text it may be next to, so it looks like a regular link
- Added link variant examples to EsButton docs page
- Added a prop table to EsButton docs page
- Fixes a small issue with EsCollapse introduced in #501 where the expand/collapse button was slightly shorter than it should be in cases where it contained large text (it now aligns horizontally with the text content beneath it even better than it did prior to the introduction of the issue)
- Fixes an issue with EsViewMore introduced in #501 where the "Show Less" link was too tall (it now aligns with the text even better than it did …
> fix: issues with link variant of EsButton

- es-bs-base/scss/_buttons.scss
- es-bs-base/scss/_reboot.scss
- es-bs-base/scss/_variables.scss
- es-vue-base/src/lib-components/EsSupport.vue
- es-vue-base/src/lib-components/EsTabs.vue
- es-vue-base/tests/__snapshots__/EsSupport.spec.js.snap
- https://energysage.atlassian.net/browse/ESDS-137
- https://energysage.atlassian.net/browse/ESDS-107
- Font weight for anchor links has changed from 400 (normal) to 500 (semibold), per the design
- This includes the `link` variant of EsButton
- Font size of the link in EsSupport has changed from 16px to 14px, per the design
- _(this was forced by making the links semibold, as the headline text in EsSupport then had almost the same weight as the link below)_
- Font weight for active tabs has changed from 600 (bold) to 700 (bolder), per the design
- _(had to modify tabs anyway to retain inactive tab font weight of 400 - since they're anchor tags and would otherwise get the 500 weight - and noticed the design for active tabs differed from the code)_
- Viewed every page of `es-design-system` …
> fix: made links semibold by default, adjusted font on EsSupport & EsTabs

- es-bs-base/scss/_variables.scss
- es-bs-base/scss/utilities/_text.scss
- es-bs-base/scss/variables/_type.scss
- es-design-system/components/ds-color-swatch.vue
- es-design-system/pages/atoms/typography.vue
- es-vue-base/src/lib-components/EsFormInput.vue
- es-vue-base/src/lib-components/EsReview.vue
- es-vue-base/src/lib-components/EsSupport.vue
- es-vue-base/tests/__snapshots__/EsReview.spec.js.snap
- es-vue-base/tests/__snapshots__/EsReviewModal.spec.js.snap
- es-vue-base/tests/__snapshots__/EsSupport.spec.js.snap
- https://energysage.atlassian.net/browse/ESDS-142
- Added new static font size utility classes based on a numbered naming scheme (e.g. 50, 75, 100, 200, etc.)
- Added new responsive font size utility classes based on the same numbered naming scheme (e.g. `font-size-lg-400`)
- Upgraded the tables on the Typography docs page to be responsive (for both font size and font weight)
- Deprecated the old font size utility classes (e.g. `font-size-sm`)
- Updated all usages within ESDS of the deprecated classes with the new ones
- Tested Typography docs page in Chrome responsive devtools, Firefox, and Safari
- Tested a `<p>` tag using a different responsive font size utility class at every breakpoint to verify correct generation of utility classes
> feat: responsive font size utility classes

- es-design-system/pages/molecules/es-form-input.vue
- es-vue-base/src/lib-components/EsFormInput.vue
- es-vue-base/tests/__snapshots__/EsForminput.spec.js.snap
- es-vue-base/tests/__snapshots__/EsReviewModal.spec.js.snap
- https://energysage.atlassian.net/browse/ESDS-133
- Added a `prefixIcon` slot to EsFormInput that positions the given icon on the left side of the input
- Upgraded the two ZIP code example inputs on the EsFormInput docs page to have proper keyboard and autocomplete hinting
- Tested in Chrome responsive devtools, Firefox, Safari
- Tested on iPhone/Android emulator with LambdaTest, confirmed numeric keyboard shows up
> feat: added prefix icon capability to EsFormInput

- es-bs-base/scss/mixins/_buttons.scss
- es-design-system/pages/molecules/es-button.vue
- https://energysage.atlassian.net/browse/ESDS-147
- Outline buttons now have a white background instead of a transparent background, matching the ESDS Figma and allowing them to be used in containers with a dark background (like the new nav CTA bar)
- Added a section to the EsButton docs page showing the four primary variants against a commonly-used dark background color
- Loaded docs page and observed new white background
> fix: outline buttons now have white background

- es-bs-base/scss/_variables.scss
- es-bs-base/scss/variables/_grays.scss
- es-design-system/pages/atoms/color.vue
- https://energysage.atlassian.net/browse/ESDS-150
- Added new `gray-150` color of `#F8F8F8`
- Colors page shows it in the Grayscale section
- Ensured the `bg-gray-150` class rendered correctly on Colors docs page
- Tested `text-gray-150` using dev tools as well
> feat: added new gray-150 color

- es-bs-base/scss/_nav.scss
- es-design-system/pages/organisms/es-nav-bar.vue
- es-vue-base/src/lib-components/EsNavBar.vue
- es-vue-base/src/lib-components/EsNavBarAccountMenu.vue
- https://energysage.atlassian.net/browse/CED-504
- Added a sticky nav bar to `EsNavBar` that animates in as soon as the user scrolls past the nav, and animates back out as soon as the nav scrolls back into view
- Utilized intersection observer for performant updating of scroll state
- Converted the desktop account menu into a reusable component so it could be used in both the regular nav and the sticky nav
- Does not appear at all on mobile
- Tested in Chrome responsive devtools, Firefox, Safari
> feat: added sticky nav bar

- es-bs-base/scss/_nav.scss
- es-vue-base/src/lib-components/EsNavBar.vue
- es-vue-base/src/lib-components/EsNavBarProductMenu.vue
- es-vue-base/src/lib-components/EsNavBarTopicMenu.vue
- https://energysage.atlassian.net/browse/CED-514
- https://energysage.atlassian.net/browse/CED-515
- Fixed issue where Home Solar mobile nav had a horizontal scrollbar
- Fixed issue where Home Solar mobile nav link border was not full width
- Fixed issue where third-level mobile nav title was not properly indented
- Tested in Chrome responsive devtools at iPhone SE and iPhone 12 Pro widths
- Tested desktop menu in Chrome, Firefox, Safari to ensure no layout regressions were introduced
> fix: mobile nav indentation and layout fixes

- es-vue-base/src/lib-components/EsFooter.vue
- es-vue-base/src/lib-utils/footer-content.js
- es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
- https://energysage.atlassian.net/browse/CED-509
- Fixes an issue where the EnergySage logo in the footer wasn't linking to the domain specified in the env variable
- Moves out the remaining hardcoded text and link content in EsFooter to the separate content object
- `energy.gov` link now opens in a new tab
- Tested passing in `https://www.google.com` as the first argument to `getEsFooterContent` and observed all the appropriate links updated their destinations, including the EnergySage logo
- Confirmed locally that all the moved-out content was still rendering properly on the page
> fix: moved out hardcoded footer link and content

- es-bs-base/scss/_reboot.scss
- es-design-system/pages/atoms/typography.vue
- es-design-system/pages/organisms/es-support-card.vue
- es-vue-base/src/lib-components/EsSupportCard.vue
- https://energysage.atlassian.net/browse/CED-484
- Lowers the font weight of `<b>` and `<strong>` tags from `700` to `600` to better match the new, lighter default font weight for body text
- Updated the Typography docs page to include a bold sentence within the paragraph example to show the treatment for bold text
- Changed the wrapper element for the `description` slot of `EsSupportCard` from `<p>` to `<div>` to allow for more flexibility in what markup can live inside it
- Provided a new `image` slot for `EsSupportCard` so consuming applications can completely replace the image component used if desired, and made the `imageAltText` and `imageSrc` props no longer required
- Updated the `EsSupportCard` docs page to describe the props and slots updates
- Tested in Chrome responsive …
> fix: default bold font weight, EsSupportCard flexibility

- es-vue-base/src/lib-components/EsFooter.vue
- es-vue-base/src/lib-components/EsNavBar.vue
- es-vue-base/src/lib-components/EsNavBarAccountMenu.vue
- es-vue-base/src/lib-components/EsNavBarFeaturedArticle.vue
- es-vue-base/src/lib-components/EsNavBarLink.vue
- es-vue-base/src/lib-components/EsNavBarProductMenu.vue
- es-vue-base/src/lib-components/EsNavBarTopLevelMenu.vue
- es-vue-base/src/lib-components/EsNavBarTopicMenu.vue
- es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
- https://energysage.atlassian.net/browse/CED-509
- All links in `EsFooter` and `EsNavBar` now use a new `EsNavBarLink` component
- `EsNavBarLink` by default renders a `<b-link>` tag - if the `href` it's given as a prop starts with a `'/'`, it passes it to the `<b-link>` as a `to` prop, otherwise uses an `href` prop - this will allow consuming Nuxt applications (if they pass in a customized set of links to `EsFooter` or `EsNavBar`, some of which are root-relative rather than absolute) to navigate between Nuxt pages like a single-page application without full page reload
- First tested this by cloning all EsNavBar code into a Nuxt app and confirming that SPA behavior occurred on root-relative URLs and normal link behavior occurred on other URLs
- Confirmed that a simpler approach of …
> feat: EsFooter and EsNavBar links are now SPA-compatible

- es-vue-base/src/lib-components/EsAccordion.vue
- es-vue-base/tests/__snapshots__/EsAccordionList.spec.js.snap
https://energysage.atlassian.net/browse/ESDS-141
* This is a small tweak: If question text wrapped in EsAccordion (mostly on mobile), the fixed height of `es-button` didn't leave enough padding.  Set height to `h-auto` instead, padding now consistent across viewports.
* Tested manually on all viewports
> fix: spacing on EsAccordion for long text

- es-bs-base/scss/_nav.scss
- es-vue-base/src/lib-components/EsNavBarProductMenu.vue
- es-vue-base/src/lib-utils/nav-bar-global-content.js
- https://energysage.atlassian.net/browse/CED-710
- https://energysage.atlassian.net/browse/CED-711
- https://energysage.atlassian.net/browse/CED-718
PR with ripped nav on es-site: https://github.com/EnergySage/es-site/pull/8453
- Added trailing slash to solar calculator link 
- Changed cursor behavior in menus
- Removed `data-toggle: dropdown` attribute in product menu links
- Tested locally for symptoms described in each ticket
- Tried to test the click-ability of product menu links in prod by removing event listeners [like I did for CED-391](https://energysage.atlassian.net/browse/CED-391?focusedCommentId=32314). It looks like 2 event listeners have to be removed/disabled - one depends on the `data-toggle` attribute, and the other might depend on the `dropdown` or `dropdown-toggle` …
> fix: CED-710 Navigation/homepage post-launch fixes

- es-design-system/pages/organisms/es-cta-banner.vue
- es-design-system/pages/organisms/es-zip-code-form.vue
- es-vue-base/src/lib-components/EsCtaBanner.vue
- es-vue-base/src/lib-components/EsCtaCard.vue
- es-vue-base/src/lib-components/EsZipCodeForm.vue
- https://energysage.atlassian.net/browse/CED-664
- Fixed an issue with EsCtaCard where images without an inherent width wouldn't display
- Fixed an issue with EsZipCodeForm where error message text was difficult to read in dark mode
- Added a new `constrained` prop to EsZipCodeForm so it is able to display within constrained-width layouts
- Removed `lgFirst` and `lgSecond` props from EsCtaBanner, in favor of a simpler (and more prescriptive) approach with new props `hasButton` and `variant`, which control font size, column layout, and side padding.
- Added new docs examples for EsCtaBanner for the `wide` variant and corrected the column width of the width-constrained banners to be more realistic.
- Tested with the old and new examples on the docs pages for the components
> Enhancements to EsCtaBanner, EsCtaCard, EsZipCodeForm

- es-design-system/pages/molecules/es-file-input.vue
- es-vue-base/src/lib-components/EsFileInput.vue
#113
The `uploadUrls` prop now can take in an optional `additionalFields` param. This will be added as form data to the upload. The `file` object is now sent as form data in a `multipart/form-data` post. Also fixed the`es-form-msg` in the example page.
These changes were required to allow uploads to the Olympus microservice. Since the `additionalFields` is optional, the change should be generic enough to be used elsewhere.
Manual testing with uploading files to Olympus.
- Test the component out in the example page. You can try using [beeceptor.com](https://beeceptor.com/)
- If you want to use Olympus, you will have to add the `additionalFields` key/value under the `onSubmit` method in `es-design-system/pages/molecules/es-file-input.vue` (L300).
> Fix: Add Additional Form Fields

- es-vue-base/src/lib-components/EsCtaBanner.vue
- es-vue-base/src/lib-components/EsCtaCard.vue
- https://energysage.atlassian.net/browse/CED-860
- change from `<h2>` to `<div role="heading" aria-level="2">` wrapper of the slot that accepts the heading tag for `EsCtaCard` and `EsCtaBanner`
Manual testing - [EsCtaCard](http://localhost:8500/organisms/es-cta-card), [EsCtaBanner](http://localhost:8500/organisms/es-cta-banner)
> fix(bug): change CTA headlines to not use a heading tag

- es-vue-base/src/lib-components/EsReviewModal.vue
- https://energysage.atlassian.net/browse/CSM-2802
- Before the change was made, the review column and ratings column in ReviewModal had no space in between. After the changes in this PR, there is a 0.75rem right padding in the ratings column in ReviewModal. 
- Check EsReviewList in Organisms. Click on 'View All Ratings' and inspect the modal. There will be a padding-right (=0.75rem) in the ratings column
- Does the spacing seems to be right (should it be less or more)?
> CSM-2802: Add Spacing Between Review Star Rating

- es-vue-base/src/lib-utils/nav-bar-global-content.js
- https://energysage.atlassian.net/browse/CED-768
- EsNavBar links were updated to point to the new VLPs on www.energysage.com in https://github.com/EnergySage/es-ds/pull/1138, but the CSM and HPM links that were previously linking to a subdomain (and therefore were set to open in a new tab) were not changed to no longer open in a new tab. This PR makes that change.
- Tested clicking all links locally
- Overall
> fix: stop the new VLP links from opening in a new tab

- es-design-system/package-lock.json
- es-design-system/pages/molecules/es-collapse.vue
- es-vue-base/src/lib-components/EsCollapse.vue
[ESDS-162](https://energysage.atlassian.net/browse/ESDS-162)
Adds `prioritizeSuggestedVisible` to the `ESCollapse` component. When false, the `visible` prop is ignored once the user interacts with the collapse. When true, the `visible` prop begins affecting the component even when the user interacts with it.
- Ensured existing functionality behaves as expected
- Turned on and off the priority toggle, and made sure the behavior was as expected
Nathaniel 👀
[ESDS-162]: https://energysage.atlassian.net/browse/ESDS-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: toggle programmatic collapse priority for es-collapse

- es-design-system/pages/organisms/es-zip-code-form.vue
- es-vue-base/src/lib-components/EsFormInput.vue
- es-vue-base/src/lib-components/EsZipCodeForm.vue
- es-vue-base/tests/__snapshots__/EsForminput.spec.js.snap
https://energysage.atlassian.net/browse/CED-930
- Make it possible for the zip code form to remain side-by-side all the way down to the smallest breakpoint (`xs`)
- Make it possible to hide the privacy section on the zip code form
- These changes are needed to create a CTA that emulates the current Django CMS banner.
Manual
- General
> CED-930: zip form tweaks

- es-design-system/pages/molecules/es-file-input.vue
- es-vue-base/src/lib-components/EsFileInput.vue
- https://energysage.atlassian.net/browse/CSM-2855
- Earlier we wouldn't trigger/display any message when the user tried to upload  a folder but now we do
- Run `es-ds` in local using `make dev`. Adding a folder would trigger/emit `fileTypeError`
> CSM-2855: Displaying an error if empty folder is added

- catalog-info.yaml
NON FEATURE CHANGE
This is a yaml file which is used to have our own internal services read information from this repo. It will have no impact on the core features or execution or usage of this module. 
* Added `description` field to metadata ([description-optional docs](https://backstage.io/docs/features/software-catalog/descriptor-format/#description-optional))
* Added a `link` just to test out putting something there, it links to the org's page on github for this one ([links docs](https://backstage.io/docs/features/software-catalog/descriptor-format/#links-optional))
* changes the spec type to `library` which is for npm modules and such ([spec type docs](https://backstage.io/docs/features/software-catalog/descriptor-format/#spectype-required))
* changed `lifecycle` to experimental …
> chore: Tweaks to catalog-info.yaml

- es-design-system/components/ds-atoms-list.vue
- es-design-system/components/ds-examples-list.vue
- es-design-system/components/ds-link-list.vue
- es-design-system/components/ds-link.vue
- es-design-system/components/ds-molecules-list.vue
- es-design-system/components/ds-organisms-list.vue
- es-design-system/layouts/default.vue
- es-design-system/pages/index.vue
- n/a
- For easier navigability and discoverability on desktop, exposed the side nav and made it persistent on the `xl` and `xxl` breakpoints (i.e. as soon as there's enough room) - reduces the need to dive in and out of category pages to navigate between child/leaf pages (i.e. fewer clicks) and gives newcomers an idea, at a single glance, of what our design system contains
- Retained `<b-container>` around the page content so it still goes up to the full max width, except on lower `xl` breakpoint where it's slightly constrained below its max width
- Enhanced the navigation to indicate the current page within its list of links
- Fixed a typo on the home page
- EsNavBar and EsFooter pages are unchanged, as those use a different layout, need to display at full viewport width, and are being …
> feat: made side nav persistent on XL and XXL breakpoints

- es-design-system/pages/organisms/es-zip-code-form.vue
- es-vue-base/src/lib-components/EsZipCodeForm.vue
https://energysage.atlassian.net/browse/GROW-33
_Please read the approaches required to complete the above ticket mentioned in the comment section of the ticket._
**Brief Overview:**
Growth would like to test pre-populating zip code, currently there is no way to send an initial ZipCode to the es-zip-code-form used everywhere. The initial value could be via pre-populating the zipcode  through google maps api or may be something else in future.
The crux however, remains that as every repo is slowly transitioning to use the `EsZipCodeForm` from in es-ds, it makes sense to have this functionality in this new zipCodeForm without disrupting the current functionality.
**Changes**
- Added optional variable `zipCodeInitialValue` to `EsZipCodeForm.vue`
- Set the data field `zipCode` to take value …
> feat: add optional initial zip code value

- es-design-system/pages/molecules/es-horizontal-list.vue
- es-vue-base/src/lib-components/EsHorizontalList.vue
https://energysage.atlassian.net/browse/CED-1444
Updated `EsHorizontalList` to the ESDS 2.0 theme
manual testing
- There's a discrepancy in the figma, as it says "Disabled icon is grey 500", but it's actually displaying gray 600. I'm using gray 500 since that's explicitly stated, and matches what's used in the pagination component.
- This component is custom-designed, and is not accessible at all. I suppose it's outside the scope of this PR to fix, but what do you think about adding a note to the documentation of this component that using it should be avoided due to accessibility? In our repos, I see it's used for `ArticleRelated` currently.
> CED-1444: horizontal list

- es-bs-base/scss/_nav.scss
- es-vue-base/src/lib-components/EsNavBar.vue
- es-vue-base/src/lib-components/EsNavBarTopLevelMenu.vue
- [CED-1484: EsNavBar: remove chevrons and other fixes](https://energysage.atlassian.net/browse/CED-1484)
- Removed chevrons from primary navbar items
- Right-align product menu items with account menu icon in LG viewport by removing right padding from final menu item
- Don't apply top padding to logo and account menu when navbar is affixed
- Changes didn't affect mobile version, just desktop
- I replaced a CSS selector for the padding with some simpler utility classes. The sticky navbar uses different markup.
- The `pt-150` padding over the logo will need to be tweaked when we start using the new logo. The current design shows `16px` above all navbar elements in that section and another `6px` in the logo itself. I approximated that `22px` with `pt-150`, which works out …
> CED-1484: EsNavBar tweaks

- es-vue-base/src/lib-components/EsFormInput.vue
- es-vue-base/src/lib-components/EsFormTextarea.vue
- es-vue-base/tests/__snapshots__/EsFormTextarea.spec.js.snap
- es-vue-base/tests/__snapshots__/EsForminput.spec.js.snap
https://energysage.atlassian.net/browse/CED-1498
- Remove italics from form labels
- Remove the font weight override so that the weight matches the Figma
Manual testing on http://localhost:8500/organisms/es-form
- General
> CED-1498: form label style update

- es-bs-base/scss/_breadcrumb.scss
- es-design-system/pages/molecules/es-breadcrumbs.vue
- https://energysage.atlassian.net/browse/CED-1513
- Override the default bottom margin for `<li>` tags in the case of EsBreadcrumbs to prevent wrapped breadcrumbs on mobile from pushing content below the fold unnecessarily
- Tested locally on EsBreadcrumbs docs page with new longer example
- Overall
> fix: breadcrumbs bottom margin

- es-vue-base/src/lib-components/EsNavBarTopLevelMenu.vue
https://energysage.atlassian.net/browse/CED-1593
- Fixes the nav bar inconsistent font weights by reusing elements rather than having separate ones conditional on `link`
- Tested locally on mobile and desktop at http://localhost:8500/organisms/es-nav-bar
- General
> CED-1593: nav bar font weights

- es-design-system/pages/organisms/es-zip-code-form.vue
- es-vue-base/src/lib-components/EsZipCodeForm.vue
- Excluded `justify-content-center` from EsZipCodeForm.vue template 
- Updated es-zip-code-form.vue template to have the zip code forms centered. 
- tested on http://localhost:8500/organisms/es-zip-code-form
- Does the layout for "Constrained stacked example" look all right for `lg` and above viewports
> fix: updated es zip code form to not be centered

- es-design-system/pages/atoms/color.vue
- n/a
- Added chart colors to Colors docs page for documentation and reference purposes, so the Shopping Experience team can reference now, and CED can reference later when doing charts
- Intentionally did not add them as SASS variables, as they should not be used as background colors or text colors; only in charts and data, which are generally specified in JS (but don't yet have a direct use case in the wild)
- Captured a potential TODO to move the color values into JS const variables in es-vue-base, though that might be our first instance of exporting JS const variables from es-vue-base so worth discussing later
- Overall
> feat: added chart colors to Colors docs page

- es-design-system/components/ds-es-logo.vue
[CED-1646: Design System: EnergySage logo gets clipped along right edge](https://energysage.atlassian.net/browse/CED-1646)
- Increased viewbox of `ds-es-logo.vue` to allow SVG to scale without being clipped by bounding box
- I didn't see any CSS that set a specific width for the logo
- Tested navbar and footer locally at http://localhost:8500/organisms/es-nav-bar
- Logo looks fine at any page magnification
- Are there any downsides to doing this?
> fix: increase viewbox length of es logo

- es-bs-base/scss/modules/border-radius-components.module.scss
- es-bs-base/scss/modules/border-radius.module.scss
- es-ds-docs/pages/atoms/corners.vue
[CED-1732: Add the Corners atoms page](https://energysage.atlassian.net/browse/CED-1732)
- Created corners atom for es-ds 3.0
- Created SCSS modules for `border-radius` and `border-radius-components`
- Followed example of atom `color.vue` for Prism code
- Test locally at http://localhost:8500/atoms/corners
- I'm working on resolving several similar TypeScript errors inside the `borderRadius` computed property. I'm not sure what's causing them.
```txt
- Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.\n  No index signature with a parameter of type 'string' was found on type '{}'.
- Parameter 'simpleName' implicitly has an 'any' type.
```
- I'm confused about why the XL breakpoint seems to kick in at 1080px instead of 1200px, and why …
> feat: corners atom for es-ds 3.0

- es-bs-base/scss/modules/breakpoints.module.scss
- es-bs-base/scss/modules/max-widths.module.scss
- es-ds-docs/pages/atoms/layout.vue
[CED-1734: Add the layout atom page](https://energysage.atlassian.net/browse/CED-1734) 
- Created layout atom for es-ds 3.0 
- Created SCSS module for `breakpoints` and `max-widths`
- Refactored previous `b-table` into `ds-responsive-table`
- Changed font color for dark background for clarity
- Tested locally at http://localhost:8500/atoms/layout
- I have a type error that sometimes shows up. A potential fix is `item[field.key as keyof typeof item]` but I was wondering if there is a better fix. 
- I added a `&nbsp;` and `md="1.5"` to fix the table spacing, but I was wondering if there is a better solution.
> feat: layout atom for es-ds 3.0

- es-bs-base/scss/_custom-forms.scss
- es-ds-components/components/es-radio-button.vue
- es-ds-docs/components/ds-molecules-list.vue
- es-ds-docs/pages/molecules/radio-button.vue
https://energysage.atlassian.net/browse/CED-1753
Globally styles PrimeVue radio buttons to match the [custom styling done for viz id on BFormGroup and BFormRadioGroup radio buttons](https://design.energysage.dev/molecules/radio-button) and created a “Radio button” molecule docs page 
Tested inline, stacked, and disabled radio button groups with focus and hover states locally at http://localhost:8500/molecules/radio-button
- I attempted to avoid regressions by adding new classes, is the resulting css too complicated? In addition, `has` is a relatively [new css feature](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) and may not be supported by older devices or browsers.
- `PrimeVue RadioButton` is a tad finicky and will not work if any props vary from the example, should a component …
> feat: globally style PrimeVue radio buttons

- es-ds-components/components/es-tab.vue
- es-ds-components/components/es-tabs.vue
- es-ds-components/nuxt.config.ts
- es-ds-docs/components/ds-molecules-list.vue
- es-ds-docs/pages/molecules/tabs.vue
- es-ds-styles/scss/vue/components/_tabs.scss
https://energysage.atlassian.net/browse/CED-1757
- Added EsTabs and EsTab component - had to follow the EsAccordionList pattern of referencing children in the slot directly
- Added Tabs docs page
- Customized tabs styling to work with PrimeVue's TabView
- Tabs now have a nice animation on the active inkbar
- Tested locally on the docs page
- Overall
> feat: added EsTabs wrapper component for PrimeVue TabView

- es-ds-docs/layouts/default.vue
- es-ds-docs/layouts/fullWidthComponent.vue
- n/a
- In order to better be a showcase and example for all EnergySage teams on how our layout and max-width container works, most pages on the design system site should adhere to our own max width container conventions
- When I originally added the side nav at larger breakpoints, I deliberately broke it out of the container so that the organisms that are intended to render at full width (e.g. CTA banner, support card) are able to be previewed in a manner like how they're supposed to appear on a page - however there are a limited number of these edge cases such that this behavior should not be the default layout - I've restored the default layout to a normal max width container and preserved the container breakout of the side nav in the fullWidthComponent layout for use when we build …
> feat: updated default layout to match normal max width; created fullWidthComponent layout for edge cases

- es-ds-docs/.eslintrc.json
- Small tweak for nested ternary
- Personally I really like the ternary syntax, particularly for conditions around classes being applied
> Rule tweak

- es-ds-components/components/es-error-page.vue
- es-ds-docs/components/ds-link-list.vue
- es-ds-docs/components/ds-organisms-list.vue
- es-ds-docs/pages/index.vue
- es-ds-docs/pages/organisms/error-page.vue
- es-ds-docs/pages/organisms/index.vue
Create `EsErrorPage` and associated docs page that uses `fullWidthComponent` layout
Tested locally at http://localhost:8500/organisms/error-page
- General
> feat: add EsErrorPage v3

- es-ds-components/components/es-form-textarea.vue
- es-ds-docs/components/ds-molecules-list.vue
- es-ds-docs/pages/molecules/form-textarea.vue
https://energysage.atlassian.net/browse/CED-1758
Adds molecule `EsFormTextarea` based off of [existing implementation](https://design.energysage.dev/molecules/es-form-textarea/) that uses HTML element `textarea`. I initially tried using [PrimeVue's](https://v3.primevue.org/textarea/) `Textarea` component but the unstyled mode is essentially the same as `textarea`.
Tested locally at http://localhost:8500/molecules/form-textarea ensuring the entered value propagates across all input fields, excluding the success state fields which have their own message
- A few things to note:
- I tried `v-bind="$attrs"` but ended up using `modelValue` when that worked with neither `Textarea` nor `textarea`
- hover, active, and focus pseudo-classes match existing implementation rather than ESDS 2.0 design
- …
> feat: add EsFormTextarea v3

- es-ds-components/components/es-file-preview-modal.vue
- es-ds-components/components/es-modal.vue
- es-ds-docs/components/ds-organisms-list.vue
- es-ds-docs/pages/molecules/modal.vue
- es-ds-docs/pages/organisms/file-preview-modal.vue
- es-ds-styles/scss/_modal.scss
https://energysage.atlassian.net/browse/CED-1789
Implements `es-file-preview-modal`. Mostly copied over from the old design system and switched to the composition API.  `es-modal` needed to be tweaked in order to apply all the necessary styling. Also found and fixed an accessibility issue with the modal.
Manual testing on http://localhost:8500/organisms/file-preview-modal
- General
> CED-1789: file preview modal

- .github/PULL_REQUEST_TEMPLATE.md
https://energysage.atlassian.net/browse/CED-1857
Add accessibility definition of done to the PR template. Removes some things that are redundant or irrelevant.
N/A
- General
> CED-1857: accessibility dod

- es-ds-docs/pages/examples/form-field-validation.vue
https://energysage.atlassian.net/browse/CED-1829
Uncomment `<es-form-textarea>` in form-field-validation example to be used with validation.
Tested locally at http://localhost:8500/examples/form-field-validation
- General
> feat: es-form-textarea with validation

- es-ds-components/components/es-slider.vue
- es-ds-docs/pages/molecules/slider.vue
DONT merge, just for reference.
Not really in the scope for [CED-1755](https://energysage.atlassian.net/browse/CED-1755), but I think `startingValue` should be made optional, and the default value set to the `v-model` value. It feels slightly odd to set a non-reactive startValue as well as bind to a reactive value via `v-model`.
[CED-1755]: https://energysage.atlassian.net/browse/CED-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: use v-bind in the style section

- es-ds-components/components/es-carousel.vue
- es-ds-components/nuxt.config.ts
- es-ds-components/types/es-carousel.ts
- es-ds-components/types/index.ts
- es-ds-docs/pages/organisms/carousel.vue
- https://energysage.atlassian.net/browse/CED-1900
- EsCarousel now takes `numVisible`, `numScroll`, and `breakpoints` props to customize the number of slides shown per breakpoint and number of slides that scroll on each paging event
- The `breakpoints` is set up in a way that makes sense with our breakpoints and how we use them in components like EsCol, for example, rather than conforming to PrimeVue Carousel's odd reversed max-width approach
- Renamed `autoscroll` prop to `autoPlay` and added `autoPlayInterval` prop
- Renamed `dots` prop to `showDots` and added `showArrows` prop
- Added `circular` prop
- Fixed an SSR issue with `circular` behavior where the wrong item would be briefly displayed as the first item on page load, then hydration would correct it
- ESDS is now exporting types …
> feat: expanded functionality for EsCarousel

- es-ds-components/components/es-carousel.vue
- es-ds-docs/pages/organisms/carousel.vue
- https://energysage.atlassian.net/browse/CED-2001
- Prev/next arrow buttons now appear below the carousel, on either side of the dots (if present), rather than on each side, matching the design and allowing carousel slides to align with page content
- Increased the spacing between the dots and arrows to meet tap targets criteria
- Allowed customization of gap between slides, gap between slides and controls, arrow size, and arrow color
- Fixed the issue where the mobile number of dots (usually more) would briefly appear on larger breakpoints until hydration had a chance to occur and update the number of dots accordingly
- Reduced the number of slides in the core examples from 12 to 6, in accordance with feedback from design that we don't really ever want to show 12 dots (as you would see …
> feat: fixed EsCarousel arrows and allowed customization

- es-ds-components/components/es-accordion-list.vue
- es-ds-components/components/es-tabs.vue
- es-ds-docs/pages/molecules/accordion.vue
- es-ds-docs/pages/molecules/tabs.vue
Unblocks https://energysage.atlassian.net/browse/CED-1983 and https://energysage.atlassian.net/browse/CED-1986
With the current implementation of Tabs and Accordion, you'll get errors when trying to use a `v-for` to iterate through child elements (`es-tab` and `es-accordion`), which is what many of the downstream usages do.  When we're accessing the children using useSlots() the `v-for` element shows up as one child, but we need its children in turn, so this is just doing some replacement in that case. 
Tested with the examples on both docs pages; also tested adding a hardcoded child alongside the `v-for` in both examples
- This feels a bit hacky, definitely open to suggestions if there are other methods to try!
> fix: v-for handling in EsTabs and EsAccordion

- es-ds-styles/scss/_forms.scss
- es-ds-styles/scss/_functions.scss
- es-ds-styles/scss/_list-group.scss
- es-ds-styles/scss/_popover.scss
- es-ds-styles/scss/mixins/_forms.scss
- es-ds-styles/scss/vendor/_rfs.scss
- es-ds-styles/scss/vue/components/_form-input.scss
- es-ds-styles/scss/vue/components/_table.scss
- https://energysage.atlassian.net/browse/CED-1998
- Followed the instructions at https://sass-lang.com/documentation/breaking-changes/import/ to install `sass-migrator` - I [couldn't just run it on the bootstrap.scss entrypoint](https://github.com/sass/migrator/issues/215), but I was able to run it on each individual file that the es-cms-pages server console reported deprecation warnings on, until no deprecation warnings were left
- Tested locally by linking es-ds-styles to es-cms-pages
- Overall
> fix: ran sass-migrator on files with deprecation warnings

- es-ds-components/components/es-carousel.vue
- es-ds-docs/pages/organisms/carousel.vue
Relevant to https://energysage.atlassian.net/browse/CED-1974
- Added `peekDesktop` and `peekMobile` props to `EsCarousel` because they were part of the design for the carousel on `whole-home` page, but also has come up before as something we want to support for more carousels
- Tweaked the `numDots` logic to take into account `numScroll` - the arrow placement was wonky when `numScroll` was not the same as `numVisible`
- "Customization" example on docs page http://localhost:8500/organisms/carousel
- Adding and removing one or both peek props; changing `numScroll` and `numVisible` at different viewports to test dots
-
> feat: Add peek props to carousel and update numDots calculation

- es-ds-components/components/es-accordion-list.vue
https://energysage.atlassian.net/browse/CED-2041
- Fix issue with `es-accordion` where if you allow multiple expand and set an initial expanded ID, the initial expanded one will not actually be initially expanded. This was due to incorrect type handling.
- I was not able to reproduce the issue of it needing two clicks on mobile, either on my computer or phone
- On the [docs page](http://localhost:8500/molecules/accordion), you can see that the Multiple Expand example now actually has the first one expanded as requested
- Tested that the component still works in PageAccordionV2 in es-cms-pages (using `npm link`) at https://app.storyblok.com/#/me/spaces/1006156/stories/0/0/94177/blok/ed7a592a-773c-4fc9-afa5-51554dcb73f5#fe1280e3-08d9-4c47-8e0a-5f02647aa03e
- General
> fix: accordion initial expand with multiple expand

- es-ds-components/components/es-footer.vue
- es-ds-components/components/icon/ccpa-opt-out.vue
- es-ds-components/utils/get-es-footer-content.ts
https://energysage.atlassian.net/browse/CED-2034
* Left align legal links
* Add link for “Your privacy choices” that opens the cookie preferences center. It is prefixed by the [CCPA icon](https://oag.ca.gov/privacy/ccpa/icons-download) to the left and has alt text of “California Consumer Privacy Act (CCPA) Opt-Out Icon”.
- Tested by linking `es-cms-pages` to `es-ds-components` and opening `localhost:8700` in GTM preview mode and clicking the “Your privacy choices” link.
- General
> feat: add preference center link to footer

- es-ds-components/components/es-zip-code-form.vue
https://energysage.atlassian.net/browse/CED-2115?atlOrigin=eyJpIjoiY2NiZDA2MDg1NjU0NGVkMmJiNjUzYzcwMDdhZjRhMWYiLCJwIjoiaiJ9
Previously, it was the case that because the overall hero module has a text-center on it, this text-center was also being applied to the contextMessage - which should always be left-aligned per [Asheeta's design](https://energysage.atlassian.net/browse/CED-2115?atlOrigin=eyJpIjoiY2NiZDA2MDg1NjU0NGVkMmJiNjUzYzcwMDdhZjRhMWYiLCJwIjoiaiJ9) on the ticket. The code changes here include the explicit left-alignment of the contextMessage in the EsZipCodeForm, such that no matter the context it's placed in, this contextMessage is always left-aligned. Additionally, per Asheeta's request, I've increased spacing in between the contextMessage and the zip code text field.
Locally …
> fix: left-aligned the contextMessage per Asheeta's design

- es-ds-components/components/es-card.vue
- es-ds-docs/pages/molecules/card.vue
- https://energysage.atlassian.net/browse/CED-2283
- In a downstream Nuxt app, when passing a root-relative URL like `/about-us/company/` as the `href` to EsCard, it will use a `<nuxt-link>` by default, which assumes that root-relative URLs are part of the same application and attempts to navigate to it using internal navigation when clicked, rather than loading the full document - this means the link is broken and doesn't load the desired page, just a blank page
- This was breaking links downstream - found while testing https://github.com/EnergySage/es-cms-pages/pull/994 on int at https://int.www.energysage.dev/authors/ (scroll to bottom and click the About Us card)
- Tested locally at http://localhost:8500/molecules/card to ensure the examples all still worked
- Tested locally by …
> feat: fix EsCard bug that forces all root-relative URLs to be an internal navigation

- es-ds-components/components/es-collapse.vue
https://energysage.atlassian.net/browse/CED-2203?atlOrigin=eyJpIjoiMWI5Njg5ZTkyNzM5NDAzYzk5NmZiN2E2NzYyODMwOTkiLCJwIjoiaiJ9
Previously, screen readers announced an incorrect header for the EsCollapse toggle. This change updates EsCollapse to use aria-labelledby on the header slot, so that the correct text is announced.
Tested locally at http://localhost:8500/molecules/collapse. The tab key focuses the toggle button and pressing Enter expands and collapses the panel. I also used VoiceOver on macOS so the toggle button now announces the correct header text through aria-labelledby. Images of using tab key to focus the toggle button and pressing enter, as well as using VoiceOver, is attached.
general
> fix: update EsCollapse to use aria-labbeledby for accessibility

- es-ds-components/components/es-tabs.vue
- https://energysage.atlassian.net/browse/CORE-6387
- filter out the comments from the initialChildren that are extracted from the slot 
- Tested locally on docs page:
- confirmed existing functionality did not change
- checked that passing an es-tab with a v-if="false" can still render 
- checked that adding in comments into the slots still allows the component to render  
used the following in the docs page to test on main branch vs. this one 
```
<es-tabs>
<es-tab title="Item one">
<p>Content one</p>
</es-tab>
<es-tab title="Item two">
<p>Content two</p>
</es-tab>
<es-tab title="Item three">
<p>Content three</p>
</es-tab>
<es-tab 
v-if="false"
title="Item four">
<p>Content four</p>
</es-tab>
</es-tabs>
```
- Any better/cleaner ways to filter out the unnecessary children here?
> fix: es-tabs when comments are children  

- es-ds-components/components/es-popover.vue
- es-ds-docs/pages/molecules/popover.vue
- n/a
- All previous iterations of EsPopover had hardcoded right-side padding across the entire height of the popover contents in order to make room for the close button - this PR floats the close button to the right so text and other content can go full width beneath it and better make use of all available space (especially helpful for when the popover contains a lot of text)
- Because of this, the `cta` slot is no longer needed to allow buttons to go full width, so it's kept for backwards compatibilty but silently deprecated and no longer documented
- Tested locally on EsPopover and EsTooltip docs pages
- Tested by npm linking to Pages and viewing solar data explorers page
- Overall
> feat: simplify EsPopover layout and allow text to go full width

- CHANGELOG.md
- README.md
- es-ds-components/components/es-popover.vue
- es-ds-components/components/es-tooltip.vue
- es-ds-components/nuxt.config.ts
- es-ds-components/package-lock.json
- es-ds-components/package.json
- es-ds-docs/eslint.config.mjs
- es-ds-docs/package-lock.json
- es-ds-docs/package.json
- es-ds-styles/package-lock.json
- es-ds-styles/package.json
https://energysage.atlassian.net/browse/CED-2358
- Upgraded to Nuxt 3.17, alongside other dependency upgrades that happen as a result of clearing out `node_modules` and `package-lock.json`.
- Wrap the Reka UI based components (Tooltip and Popover) in ClientOnly when in the dev server, which prevents the SSR issue.
- Other ideas from [Eric's troubleshooting doc](https://docs.google.com/document/d/1nmgm4RG9s1UsGF0ra5yV-uGWJvqHXsfdcoQOQdivPr8/edit?tab=t.0) were attempted without success. Also tried aliasing instances of Vue modules using Vite, as well as forcing deduplication. Using Yalc instead of npm link could be an alternative (and seems to be what people do with React due to analogous issues), but I think it's a lot simpler to just have this ClientOnly workaround since only two …
> fix: upgrade to nuxt 3 17

- CHANGELOG.md
- es-ds-components/components/es-modal.vue
- es-ds-components/package-lock.json
- es-ds-components/package.json
- es-ds-docs/package-lock.json
- es-ds-docs/package.json
- https://energysage.atlassian.net/browse/CED-2488
- Fixes the no-header modal example's accessibility so that focus is again given to the modal when it opens (its focus trap was already working, but you had to tab through the whole page before you'd get put into it)
- Accomplishes this by retaining the close button even when the `closeable` prop is set to false, because [PrimeVue's focus logic](https://github.com/primefaces/primevue/blob/3.53.0/components/lib/dialog/Dialog.vue#L198) searches for elements with an `autofocus` attribute, and failing that, gives focus to the close button (which before this change, didn't exist, so it gave focus to nothing)
- This has the added benefit of meaning the no-header modal is closable via Esc key (because PrimeVue requires the `closeable` prop to be …
> fix: modals without headers are now accessible

- es-ds-components/components/es-form-msg.vue
https://energysage.atlassian.net/browse/CED-2506
We are using EsFormMessage on the edit details page of HomeScore, and realized that the `my-100` style is not easily overridden. This styling should be set by app using this component.
Tested on http://localhost:8500/molecules/form-message, the docs page already had `class='my-100'` that was being overridden.
- General
> fix: remove unoverridable margin from form message

- es-ds-components/components/es-form-radio-card.vue
- Ensure `name` is getting set for radio card
-
> fix: input attribute name

- es-ds-components/components/es-progress.vue
- es-ds-docs/pages/molecules/progress.vue
- https://energysage.atlassian.net/browse/CED-2616
- Realized while attempting to have a thicker progress bar on mobile than on desktop based on feedback from design that this wasn't possible because the `height` prop wasn't flowing into a `computed()` value, just an object that was initialized once and never changed
- Fixed this so `height` is now reactive
- Added an example to the Progress docs page to demonstrate dynamic height changing
- Tested on the Progress docs page
- Overall
> fix: bug with EsProgress preventing height prop from being reactive
