EnergySage/es-ds

es-design-system/pages/molecules/es-popover.vue, es-vue-base/src/lib-components/EsPopover.vue, es-vue-base/tests/EsPopover.spec.js, es-vue-base/tests/__snapshots__/EsPopover.spec.js.snap, es-vue-base/tests/utils.js
ESDS-53 EsPopover Tests and Link
- https://energysage.atlassian.net/browse/ESDS-53
- added custom color and updated `font-weight` for links in `EsPopover`
- updated tests for `EsPopover` based on Bootstrap Vue's test [here](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/popover/popover.spec.js), which adds popover to the `document` so that `props` are testable but doesn't add code for popover to `html()`, so I removed the snapshot file
- added `utils` based on Bootstrap Vue's [here] (https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/tests/utils.js)
- made use example more similar to Figma design
- Manual
- I wasn't able to achieve all of the same tests as the Bootstrap Vue example, but the tests definitely look a lot better than they did before... do we want …
=> ESDS-53 EsPopover Tests and Link

es-design-system/pages/organisms/es-review.vue, es-vue-base/src/lib-components/EsReview.vue, es-vue-base/tests/EsReview.spec.js, es-vue-base/tests/__snapshots__/EsReview.spec.js.snap
- https://energysage.atlassian.net/browse/ESDS-70
- added `updatedComment` prop to `EsReview`
- updated docs and tests with new prop
- Manual testing
- Change the `updated_comment` field in `reviews` in `es-review.vue`. The updated comment should always get shown, if it exists.
=> ESDS-70 Added updated comment to EsReview

.github/workflows/ci.yml, CHANGELOG.md, Makefile, README.md, es-design-system/layouts/default.vue, es-design-system/nuxt.config.js, es-vue-base/build/rollup.config.js, es-vue-base/package-lock.json, es-vue-base/package.json
=> Fix es-ds-build

.gitignore, es-bs-base/scss/_variables.scss, es-bs-base/scss/variables/_colors.scss, es-bs-base/scss/variables/_global-settings.scss, es-bs-base/scss/variables/_grays.scss, es-bs-base/scss/variables/_spacers.scss, es-bs-base/scss/variables/_theme-colors.scss, es-design-system/components/ds-atoms-list.vue, es-design-system/components/ds-link-list.vue, es-design-system/components/ds-molecules-list.vue, es-design-system/components/ds-organisms-list.vue, es-design-system/layouts/default.vue, es-design-system/nuxt.config.js, es-design-system/package-lock.json, es-design-system/package.json, es-design-system/pages/atoms/color.vue, es-design-system/pages/atoms/grids.vue, es-design-system/pages/atoms/icons.vue, es-design-system/pages/atoms/space.vue, es-design-system/pages/atoms/typography.vue, es-design-system/pages/bootstrap-4.vue, es-design-system/pages/index.vue, es-design-system/pages/molecules/es-breadcrumbs.vue, es-design-system/pages/molecules/es-button.vue, es-design-system/pages/molecules/es-form-input.vue, es-design-system/pages/molecules/es-form-textarea.vue, es-design-system/pages/organisms/es-form.vue, es-vue-base/src/lib-components/EsRating.vue
-
- Removed complete bootstrap import from `:export` files in favor of only mixins/functions; this resulted in all bootstrap CSS being included in bundles
- Update nuxt configuration to tree shake `bootstrap-vue` components and directives
- Added `null-loader` to always exclude icons from `bootstrap-vue`
- Removed inline imports for `bootstrap-vue` components
- 
- Reran tests & builds
=> Clean up bootstrap exports & bootstrap-vue imports

es-design-system/pages/organisms/es-form.vue, es-vue-base/src/lib-components/EsFormInput.vue
- https://energysage.atlassian.net/browse/ESDS-92
- Added `tel` to the list of allowed values for the `type` prop for EsFormInput
- Added `type="tel"` to the phone number field on the EsForm organism page
- Tested on iPhone/Android emulators using LambdaTest
- Overall
- Run es-design-system server, open EsForm page, observe that there are no console warnings from the use of `tel` type.
- None
=> ESDS-92 tel type for form input

es-bs-base/scss/_variables.scss
- https://energysage.atlassian.net/browse/ESDS-81
- Changed body copy color from #292929 to #404040
- Headers use a separate color variable and remain #292929
- Loaded es-design-system site in Chrome, compared to version on dev
- Overall
- Build es-bs-base
- Load es-design-system site
- View Typography page
- None
=> ESDS-81 updated body text color to match design

es-bs-base/scss/_type.scss, es-bs-base/scss/_variables.scss
- https://energysage.atlassian.net/browse/ESDS-93
- Header font size variables now come in two sets: one for mobile, one for desktop
- Header font sizes are now automatically adjusted to the mobile and desktop sizes based on the breakpoint
- Header font sizes now match the [ESDS Figma](https://www.figma.com/file/ILnQorHR2IcGAsIkme9Ctb/ESDS-1.0?node-id=59%3A538)
- H5 and H6 do not appear in the Figma for mobile but are now no larger than H4
- Mobile and desktop testing in Chrome responsive devtools
- Overall approach
- Build es-bs-base and make symlink
- Run es-design-system site and go to Typography page
- None
=> ESDS-93 match header font sizes to figma and make responsive

es-bs-base/scss/_variables.scss, es-design-system/pages/molecules/es-modal.vue
- https://energysage.atlassian.net/browse/ESDS-94
- Updated padding on modals to be inline with [design](https://www.figma.com/file/EIMLD2tQaFG5m1rA31h5QF/CSM-Log-In-Modal-Review?node-id=0%3A1) specifications
=> ESDS-94 Fix modal padding

es-bs-base/scss/_variables.scss, es-design-system/components/ds-molecules-list.vue, es-design-system/pages/molecules/es-accordion.vue, es-vue-base/src/lib-components/EsAccordion.vue, es-vue-base/src/lib-components/EsAccordionList.vue, es-vue-base/src/lib-components/index.js, es-vue-base/tests/EsAccordionList.spec.js, es-vue-base/tests/__snapshots__/EsAccordionList.spec.js.snap
- https://energysage.atlassian.net/browse/ESDS-86
- Added companion EsAccordionList and EsAccordion components per our design system Figma and as built for the Heat Pump Marketplace
- Added appropriate molecule documentation page with examples and tables of prop descriptions
- Per design, all EnergySage pages should have a background color of #FAFAFA rather than #FFFFFF, so I have made this change in the design system in this PR. This is especially important for the accordion, as it is designed with a rounded white background which doesn't stand out against a white page background.
- Added Jest tests covering all combinations of props
- Tested accordion on documentation page in Firefox, Safari, Chrome
- Tested accordion on documentation page on iPhone and Android emulator
=> feat: added EsAccordion component

CHANGELOG.md, es-bs-base/scss/_variables.scss, es-bs-base/scss/mixins/_forms.scss, es-design-system/components/ds-examples-list.vue, es-design-system/components/ds-link-list.vue, es-design-system/pages/examples/form-with-validation.vue, es-design-system/pages/examples/index.vue, es-design-system/pages/index.vue, es-vue-base/src/lib-mixins/forms.js
- https://energysage.atlassian.net/wiki/spaces/DS/pages/129925131/2022-11-29+Form+Validation
- Enables error icons in `es-bs-base`
- Add validation mixin helper method for touch validation
- Add examples section to reduce confusion around semantics of `organisms`. Includes documentation around expected validation UX
- Manual testing in the example page built
=> Tweaks to form validation

CHANGELOG.md, es-design-system/pages/organisms/es-review.vue, es-design-system/pages/organisms/es-reviews-list.vue, es-vue-base/src/lib-components/EsReview.vue, es-vue-base/src/lib-components/EsReviewModal.vue, es-vue-base/tests/EsReview.spec.js, es-vue-base/tests/__snapshots__/EsReview.spec.js.snap, es-vue-base/tests/__snapshots__/EsReviewModal.spec.js.snap
[ESDS-112](https://energysage.atlassian.net/browse/ESDS-112)
-  Resolves [ESDS-112](https://energysage.atlassian.net/browse/ESDS-112)
- In documentation (`es-review` and `es-review-list`), only pass in a `Date` object if the value exists. Setting `new Date()` passes in a date set to today's date.
- In `EsReview`, only display `modified` and the accompanying text if the value exists. `displayDate` and `displayDateText` now check for `modified` and return empty strings if it does not exist. `localeDate` now checks that a date is passed in before evaluating it.
- Visual
[ESDS-112]: https://energysage.atlassian.net/browse/ESDS-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ESDS-112]: …
=> ESDS-112 Fix default to current date in tests and update display

es-design-system/components/ds-molecules-list.vue, es-design-system/pages/molecules/es-progress.vue, es-vue-base/src/lib-components/EsProgress.vue, es-vue-base/src/lib-components/index.js
- https://energysage.atlassian.net/browse/ESDS-85
- Adds new EsProgress component and accompanying documentation
- Uses Bootstrap Vue's Progress component
- Only changes to default behavior are styling related to match our designs:
- height is defaulted to 0.3125rem (5px)
- overall component is not rounded
- component background is set to a specific color (#ddd)
- inner progress bar is rounded, to 0.125rem (2px), only when not 100%
- Decided not to include Jest tests for this component since the only functionality/logic we are adding is whether or not the border radius is applied when the value is 100%, which is purely cosmetic and probably not suitable for a Jest test
- Loaded docs page in Chrome, Firefox, Safari and tested animated transition buttons
- Loaded docs page in iPhone/Android …
=> feat: add EsProgress component

.vscode/extensions.json
Removing some vs-code recommendations for this mono-repo. Things like django and python are not used in any of the projects in this repo.
=> refactor: :recycle: reduce number of vs-code recommendations

CHANGELOG.md
- n/a
- Added v0.15.0 changelog details
- Viewed changelog preview
=> add v0.15.0 changelog

es-bs-base/scss/_variables.scss
- https://energysage.atlassian.net/browse/ESDS-125
- Updated the `h4` and `h5` mobile font size from 14px to 16px.
- Reasoning in the ticket - summary is:
- I introduced this issue
- Headings should generally not be smaller than body text (which on mobile is 16px)
- Accessibility guidelines [generally recommend](https://accessibleweb.com/question-answer/minimum-font-size/#:~:text=Answer,usually%20be%2016px%20or%20larger.) that most text shouldn't be smaller than 16px
- HPM uses `<h4>` but always has to override the font size with utility classes
- Designs don't often use 14px, and I have a specific case on homepage which could use the 16px mobile --> 20px desktop font size change.
- Chrome responsive devtools to view mobile and desktop
=> fix: mobile size of h4 and h5 is now 16px

es-bs-base/scss/_type.scss, es-bs-base/scss/_variables.scss, es-design-system/pages/atoms/typography.vue
- https://energysage.atlassian.net/browse/ESDS-124
- Added eyebrow heading class based on most common patterns seen in designs
- Added eyebrow heading examples to Typography docs page
- Added guidance to Typography page to use sentence case for headings, per marketing style guide
- Updated all headings on the Typography page to be sentence case
- Viewed new heading on docs page
=> feat: add eyebrow heading

LICENSE
- https://energysage.atlassian.net/browse/ESDS-145
- Added language to our license in the "subject to the following conditions" section outlining the use of the ES leaf logo as a trademark
- n/a
=> docs: updated license to clarify usage of ES leaf logo

es-vue-base/src/lib-components/EsFormInput.vue
- https://energysage.atlassian.net/browse/ESDS-146
- Corrects `aria-hidden` value on EsFormInput's prefix icon from empty value to `"true"`
- Confirmed the new value via Chrome devtools
=> fix: set aria hidden to valid value

es-bs-base/scss/_variables.scss
- https://energysage.atlassian.net/browse/ESDS-149
- Per design, the max-width of the XXL breakpoint has been reduced from 1610px to 1440px
- Tested ESDS site in Chrome responsive devtools before and after and confirmed new, reduced max-width was applied
=> feat: updated xxl max width to 1440px

es-design-system/layouts/footer.vue, es-design-system/pages/molecules/es-footer.vue, es-vue-base/src/lib-components/EsFooter.vue, es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
https://energysage.atlassian.net/browse/CED-432
- Open non-www links in new tabs
- Edit the text & destination of some footer links
- Restructure link columns to use a list instead of object
- Add footer-specific layout to docs so footer can be previewed in full width
- Tested manually
- ~When I click multiple links that should open in a new tab, they open in the _same_ new tab. Do you also see this, and is it an issue?~ Interesting TIL: `_blank` is new tab, `__blank` is new tab that will be reused.
=> fix: Open some footer links in new tabs

es-vue-base/src/lib-components/EsNavBar.vue
* https://energysage.atlassian.net/browse/CED-516
Accommodate the 2x first names in the DOM after addition of the sticky header.
Resolves issues with name not showing up in the sticky header.
Tested in responsive chrome logged in and logged out users and during active login/logout actions.
=> fix: sticky header account name fix

es-bs-base/scss/_variables.scss, es-design-system/pages/atoms/typography.vue
https://energysage.atlassian.net/browse/CED-692
- Heading sizes have been adjusted in es-bs-base.
- At this point new font sizes have been inserted in the _variables.scss file.
- Manual testing.
=> feat: ced-692 Adjust Heading Sizes in es-bs-base

es-vue-base/src/lib-components/EsFooter.vue, es-vue-base/src/lib-components/EsNavBarFeaturedArticle.vue, es-vue-base/src/lib-components/EsNavBarProductMenu.vue, es-vue-base/src/lib-components/EsNavBarTopLevelMenu.vue, es-vue-base/src/lib-utils/nav-bar-global-content.js, es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
https://energysage.atlassian.net/browse/CED-705
- Adds `imageAlt` prop to featured article, so that the alt can accompany each image src in `nav-bar-global-content`
- Add alt to DOE logo in footer
Manual testing
=> fix: alt on nav and footer images

es-vue-base/src/lib-utils/nav-bar-global-content.js
- https://energysage.atlassian.net/browse/CED-769
- Heat pump nav item "Get personalized quotes" now takes users to `/dashboard` instead of `/welcome`
- Followed link locally and did not see the issue
- Followed link on deployed ESDS site (old destination) and did see the issue
=> fix: issue with heat pump nav link that was directing some users to the wrong place

es-design-system/components/ds-responsive-table-column.vue, es-design-system/components/ds-responsive-table-row.vue, es-design-system/pages/atoms/typography.vue, es-design-system/pages/molecules/es-card.vue, es-design-system/pages/molecules/es-file-input.vue, es-design-system/pages/organisms/es-file-thumbnail.vue, es-design-system/pages/organisms/es-support-card.vue
- n/a
- Made `es-design-system` responsive docs tables more flexible in their column widths (they were hardcoded to certain percentages based on column order before)
- Using the new DsResponsiveTableColumn component, you can now pass in `md`, `lg`, `xl`, or `xxl` props to specify how many grid columns it should use at each breakpoint (default is `4` at `md`, because in most cases we use three columns)
- Mobile column widths remain hardcoded for now; that can be a future enhancement.
- Updated all docs pages that use DsResponsiveTable (Typography, EsCard, EsFileInput, EsFileThumbnail, EsSupportCard) to now use DsResponsiveTableColumn, and set the column widths appropriately for the content of each
- Tested on each docs page that uses DsResponsiveTable
=> feat: DsResponsiveTable column widths can now be changed

es-vue-base/src/lib-components/EsFileInput.vue
#113
- Change axios put to post
Manual
=> fix: make axios post not put

es-design-system/components/ds-examples-list.vue
#113
- Removes duplicate "Form with Field Validation" example caused by #1057 
- More specifically, these lines [here](https://github.com/EnergySage/es-ds/pull/1057/files#diff-e1155c39a311770f4b4aa91d7f95e7c8c0e4a14afd4d6d44c78b9f97beda052aR13)
- Manual testing
=> fix: remove duplicate ES example

es-vue-base/src/lib-utils/nav-bar-account-content.js
- https://energysage.atlassian.net/browse/ESDS-160
- Added registration link environmental variable; defaulted to rooftop.
- This fixes an issue when the routing service is live, after creating an account in flash, the user landed on `/` and was not logged in
- Manual
=> feat: make register link a variable

es-vue-base/src/lib-components/EsNavBarLink.vue
=> fix(navbar): remove to attribute on navbarlink

es-design-system/pages/organisms/es-support-card.vue, es-vue-base/src/lib-components/EsSupportCard.vue
https://energysage.atlassian.net/browse/CED-635 (Change will then be used in `es-cms-articles`)
- Tested appearance in all viewports; current default examples are unaffected and constrained example looks reasonable.
- The Figma design for the constrained version of this module does look slightly different; it uses a 75x75px version of the image which is also not centered.  However due to the way this image display is implemented, the fact we allow a slot for it, and the mobile version showing the 100px image regardless, I thought that particular difference would require more refactoring than it's worth.  If that's not the case, I can log a ticket to investigate matching more exactly.
=> refactor: allow constrained es-support-card

es-vue-base/src/lib-utils/footer-content.js, es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
- https://energysage.atlassian.net/browse/CED-768
- Pointed all `/market-intro` links to Home Solar VLP
- Pointed Community Solar and Heating & Cooling links to their respective VLPs, and removed new tab behavior
- Tested the links locally
- Overall
=> feat: updated EsFooter links to new VLP URLs

es-vue-base/src/lib-components/EsZipCodeForm.vue
https://energysage.atlassian.net/browse/CED-842
Increased the spacing of the form from mb-50 to mb-100 to meet tappability criteria between the submit button and the Privacy Policy Link.
Manual Testing
- Would the increased space be enough?
=> fix(bug): add bottom margin between form and link in EsZipCodeForm

es-design-system/pages/molecules/es-horizontal-list.vue, es-vue-base/src/lib-components/EsHorizontalList.vue
https://energysage.atlassian.net/browse/CED-667
In ArticleRelated desktop design, it has arrows to navigate through the horizontal list. Added a prop to have the option to use arrows in desktop. 
Manual Testing (es-design-system/pages/molecules/es-horizontal-list.vue)
=> feat: add arrows prop

es-design-system/pages/molecules/es-collapse.vue
[ESDS-162](https://energysage.atlassian.net/browse/ESDS-162)
In the most recent PR for EsCollapse, there was a typo in one of the class definitions. This resolves that.
Manual testing
[ESDS-162]: https://energysage.atlassian.net/browse/ESDS-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Styling Typo from EsCollapse

es-vue-base/src/lib-components/EsDataTable.vue
https://energysage.atlassian.net/browse/CED-915
- does not implement that component. Just makes a fix that's needed for further progress.
Export `BTable` in `EsDataTable` so that it works in downstream repos.
- General
=> CED-915: export BTable from EsDataTable

es-vue-base/src/lib-utils/footer-content.js, es-vue-base/src/lib-utils/nav-bar-global-content.js, es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
[CED-767: Update Partner/Installer Nav links (header and footer)](https://energysage.atlassian.net/browse/CED-767)
- Navbar: Added new "Work with us" section
- Navbar and Footer: Made links in "Work with us" sections the same
- Navbar and Footer: Renamed and removed some other links
- Footer: Moved two links to bottom of "Resources" section
- Tested [es-nav-bar](http://localhost:8500/organisms/es-nav-bar) and [es-footer](http://localhost:8500/organisms/es-footer) locally in Design System
=> CED-767: Update navbar and footer items

es-design-system/pages/atoms/icons.vue, es-vue-base/src/lib-icons/icon-bank.vue, es-vue-base/src/lib-icons/icon-credit-card.vue, es-vue-base/src/lib-icons/index.js, es-vue-base/tests/__snapshots__/icons.spec.js.snap
[CSM-2848](https://energysage.atlassian.net/browse/CSM-2848)
Adds two new payment icons for use in [CSM-2848](https://energysage.atlassian.net/browse/CSM-2848) (PR [here](https://github.com/EnergySage/es-cdgm/pull/3041))
Manual testing!
[CSM-2848]: https://energysage.atlassian.net/browse/CSM-2848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSM-2848]: https://energysage.atlassian.net/browse/CSM-2848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add two payment icons

es-vue-base/src/lib-components/EsFileInput.vue
- https://energysage.atlassian.net/browse/CSM-2859
- Earlier when uploading a file one _after_ another in the same session would throw an error saying "You have already uploaded a file with the name "{fileName}". Please rename your file and try again.". This was caused because when the second file was being uploaded, we were re-uploading the first file causing issues when downloading these files.
- In `es-vue-base/src/lib-components/EsFileInput.vue` now uploading only `newValidFiles` instead of all `files`
- There are 3 ways we can test these changes:
- Deploy this to production and then test out changes in `es-cdgm`
- You'll need to symlink `~/Dev/es-ds/es-vue-base/dist` to `~/Dev/-es-cdgm/frontend/node_modules/@energysage/es-vue-base` (https://docs.npmjs.com/cli/v9/commands/npm-link)
- …
=> CSM-2859: Fixing Multiple File Download Bug

CHANGELOG.md
=> chore: clean-up the changelog

es-vue-base/src/lib-utils/nav-bar-global-content.js
https://energysage.atlassian.net/browse/CED-969
- Update LFC links in EsNavBar to new URLs according to[ site migration sheet](https://docs.google.com/spreadsheets/d/1-A4om_fArblc8s5sLA7XbufWchbh4mtF2om_biABEgc/edit#gid=212067427)
- changed the news urls to www.energysage.com/blog but the content of the link might not be ready
- manual testing
- Overall
=> CED-969-update-LFC-urls-es-nav-bar

es-bs-base/scss/vendor/_rfs.scss, es-design-system/package-lock.json, es-vue-base/package-lock.json, es-vue-base/package.json
Fix regression around responsive font sizes when making the switch to modular sass
manually looking at rendered sizes in `/atoms/typography` on this branch vs. main
=> fix: ensure rfs variables properly disable rfs settings

es-vue-base/src/lib-components/EsFileInput.vue
- https://energysage.atlassian.net/browse/CSM-2971
- Removing spaces from file names
- Manual testing -- try uploading a file with spaces in its name and they spaces should be trimmed 
-
=> CSM-2971: ESFileInput - Remove Spaces from File Names

es-vue-base/src/lib-utils/footer-content.js, es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
- Fix typo on the US DOE line
-
=> Fix EsFooter DOE typo

catalog-info.yaml, mkdocs.yml
https://energysage.atlassian.net/browse/PLAT-886
Updating catalog-info.yaml file as descriptor file for dev portal.
Added:
- title
- documentation page linked
- description updated
-
=> chore:Catalog info devportal

es-design-system/pages/organisms/es-zip-code-form.vue, es-vue-base/src/lib-components/EsZipCodeForm.vue
* https://energysage.atlassian.net/browse/IDR-406
* Pass `selectedProduct` prop to `EsZipCodeForm` 
* `product` is added to the queryparams to provide more context to url
* Add CTA to the doc that accepts heatpump query param, ensure that `?product=heatpump` is added to the url on form submission
* I didn't see any automated tests for `EsZipCodeForm`. Is there anything I should add here to help validate this?
- This is my first contribution to es-ds, is there anything I should be aware of that isn't obvious?
=> feat: EsZipCodeForm accepts selectedProduct query param

es-vue-base/src/lib-utils/nav-bar-global-content.js
- https://energysage.atlassian.net/browse/CED-1336
- Updated the outdated intel report(16) with latest intel report(18) in nav-bar-global-content.js.
- Tested the changes locally (http://localhost:8500/organisms/es-nav-bar)
- Anything I have missed?
=> fix: updated the nav with latest intel report

es-vue-base/src/lib-utils/nav-bar-global-content.js
https://energysage.atlassian.net/browse/IDR-425
Enable traffic routing to nexstar flow.
- Does this change make sense here? 
- I haven't figured out a way to test this. Could you give some suggestions?
=> feat: IDR-425 update routing to enable nexstar flow

es-vue-base/src/lib-utils/nav-bar-account-content.js
https://energysage.atlassian.net/browse/CORE-5306
- Updated links using Figma mock up attached to ticket 
- In `EsNavBar.vue`, change `fetch('/api/account-first-name/'` to `fetch('http://localhost:8000/api/account-first-name/'` and add the parameter `credentials: 'include'` to the `fetch` request. This assumes you have `es-site` running locally on port `8000`
-
=> CORE-5306: Make Updates in BS4 Header

es-vue-base/src/lib-utils/nav-bar-account-content.js
https://energysage.atlassian.net/browse/CORE-5475
- Changed "My dashboard" to "My profile"
- Ran `make dev` and confirmed copy changed
- In EsNavBar.vue, change fetch('/api/account-first-name/' to fetch('http://localhost:8000/api/account-first-name/' and add the parameter credentials: 'include' to the fetch request. This assumes you have es-site running locally on port 8000
-
=> CORE-5475: Change "My dashboard" to "My profile"

es-bs-base/scss/_variables.scss, es-vue-base/src/lib-components/EsProgress.vue, es-vue-base/src/lib-components/EsProgressCircle.vue
- https://energysage.atlassian.net/browse/CED-1396
- Updated progress-circle color in EsProgressCircle.vue template to match the figma design.
- Updated the colors in EsProgress.vue and _variables.scss for EsProgress to match the figma design.
- Tested changes locally for [EsProgressCircle](http://localhost:8500/molecules/es-progress-circle) and [EsProgress](http://localhost:8500/molecules/es-progress).
=> CED 1396 update es progress es progress circle styling esds 2.0

es-design-system/pages/organisms/es-error-page.vue, es-vue-base/src/lib-components/EsErrorPage.vue, es-vue-base/src/lib-utils/error-page-content.js
https://energysage.atlassian.net/browse/CED-1416
Updates the styling of the error page for ESDS 2.0 to match the Figma.
Manual testing
- General
=> feat: new error page design

.github/workflows/deploy-v2.yml
=> fix: update branch checkout name to feature branch

es-design-system/pages/organisms/es-reviews-list.vue, es-vue-base/src/lib-components/EsReview.vue, es-vue-base/tests/__snapshots__/EsReview.spec.js.snap
https://energysage.atlassian.net/browse/CED-1445
Implements the new styling for the reviews as part of the ESDS 2.0. Lots of small styling tweaks, and one change to functionality- the verified checkmark will appear beside the reviewer on mobile rather than having the "verified" text off to the right.
- General
=> CED-1445: reviews styling update

es-bs-base/scss/vue/components/_file-input.scss, es-bs-base/scss/vue/components/index.scss, es-design-system/pages/examples/file-upload.vue, es-design-system/pages/molecules/es-file-input.vue, es-vue-base/src/lib-components/EsFileInput.vue, es-vue-base/tests/__snapshots__/EsFileInput.spec.js.snap
(https://energysage.atlassian.net/browse/CED-1452)
* Updated spacing, font size, button type, and text based on design
* Involved a refactor to move styles from es-vue-base into es-bs-base
* Discussion in Slack decided that changing the file preview is not necessary
* Tested locally on [EsFileInput](http://localhost:8500/molecules/es-file-input) and [File upload](http://localhost:8500/examples/file-upload)
* Tested on mobile
- General feedback
=> CED-1452: EsFileInput restyling

es-vue-base/src/lib-utils/nav-bar-account-content.js
-https://energysage.atlassian.net/browse/CORE-5499
- Removed Done shopping from the dropdown header
-
=> CORE-5499: Remove Done Shopping From Dropdown

es-bs-base/scss/vue/components/_tabs.scss, es-design-system/package-lock.json, es-vue-base/package-lock.json
https://energysage.atlassian.net/browse/CED-1462
Fixed some styling issues that were raised in the ticket. There are also changes to package-locks upon installing which are included here, my guess is that the last release wasn't totally finished?
Manual testing
- General
=> CED-1462: fix es-tabs

es-vue-base/src/lib-components/EsFooter.vue, es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
- https://energysage.atlassian.net/browse/CED-1576
- Removed right padding on final social icon in EsFooter so they can be fully centered on mobile
- Overall
=> fix: centered social icons in EsFooter

es-bs-base/scss/_variables.scss
- https://energysage.atlassian.net/browse/CED-1522
- Remove white background from pagination items so it works better against a non-white background
- Tested locally on EsPagination docs page by temporarily throwing a div around the example with a background color
- Overall
=> fix: removed white bg from pagination items

es-bs-base/scss/_buttons.scss, es-design-system/pages/molecules/es-button.vue
- https://energysage.atlassian.net/browse/CED-1586
- Link button font weight (except inline) is now 700 instead of 500
- Added two new "CTA link with arrow" examples to the Button docs page
- Overall
=> fix: link button font weight is now 700

es-bs-base/scss/_nav.scss, es-vue-base/package-lock.json, es-vue-base/src/lib-utils/nav-bar-global-content.js
[CED-1617: Remove redundant News link?](https://energysage.atlassian.net/browse/CED-1617)
- Qijia pointed out a duplicate navbar link to the blog in this [Slack thread](https://energysage.slack.com/archives/C04MSPPA9TL/p1718140203821579)
- Asheeta recommended the following:
- Added new selector to mobile media query
- Tested locally in design system at http://localhost:8500/organisms/es-nav-bar
- No other navbar links in mobile or desktop are affected, as far as I can tell
=> fix: navbar heading link styles

es-vue-base/src/lib-components/EsNavBarFeaturedArticle.vue
https://energysage.atlassian.net/browse/CED-1629
* Made the corners rounded of the featured article image in the nav bar under “Tips & guides” and “About us”
* Tested locally at http://localhost:8500/organisms/es-nav-bar
Before:
After:
- General
=> feat: make nav bar featured image rounded

es-vue-base/src/lib-components/EsVideo.vue, es-vue-base/tests/__snapshots__/EsVideo.spec.js.snap
https://energysage.atlassian.net/browse/CED-1628
* In order to get an embedded video to autoplay, most modern browsers require that the video be muted to support UX. Adding `mute=1` to the url enables this.
* Tested locally in Safari and Chrome on desktop and mobile
- General, maybe try in other browsers
=> feat: mute video to allow autoplay

es-vue-base/src/lib-utils/footer-content.js, es-vue-base/tests/__snapshots__/EsFooter.spec.js.snap
* https://energysage.atlassian.net/browse/PLAT-1163
* Removed Help Scoutlink from constants
* Removed Help Scout URL var from constants
* Updated snapshot so that the tests reflect the change
* Lint
* Ran unit tests (incl. snapshots)
* Visual inspection thanks to `make dev`
-
=> chore: remove Help Scout links

es-vue-base/src/lib-components/EsHorizontalList.vue
- Add `active-index` prop to EsHorizontalList slot so people can easily find which item is the active one (https://github.com/EnergySage/product-details-page/blob/main/components/product-details/ProductDetailsProductGallery.vue#L118).
- Tested `<EsHorizontalList />` locally
-
=> feat: add active-index prop to EsHorizontalList slot

.github/workflows/deploy-v3.yml
- https://energysage.atlassian.net/browse/CED-1730
- Re-set up the temporary deploy of ESDS 3.0 to new.design.energysage.dev
- Modeled file after [deploy-v2.yml](https://github.com/EnergySage/es-ds/blob/05d3460f786b2ab2b5d4364f447939aa2c12d9b8/.github/workflows/deploy-v2.yml) 
- Changed branch name to `esds-3.0-vue3-primevue` and working directory to `./es-ds-docs`
- Added step to link packages because `@energysage/es-ds-components` is in pre-release [development](https://github.com/EnergySage/es-ds/tree/esds-3.0-vue3-primevue/es-ds-components#readme) and deleted `npm install` command
- Can remove this step and add in `npm install` once the package is released
- Tested with a test trigger 
- https://github.com/EnergySage/es-ds/actions/workflows/deploy-v3.yml  
- …
=> feat: set up temporary deploy of ESDS 3.0

es-bs-base/scss/modules/spacers.module.scss, es-ds-docs/pages/atoms/spacing.vue
[CED-1735: Add the Spacing atoms page](https://energysage.atlassian.net/browse/CED-1735)
- Created spacing atom for es-ds 3.0
- Created SCSS module for `spacers`
- Deleted data constant `compCode` because it was unused
- Tested locally at http://localhost:8500/atoms/spacing
- I have two type errors created from `Parameter implicitly has an 'any' type` that show up locally. Let me know if you are also getting the type errors.
=> feat: spacing atom for es-ds 3.0

es-bs-base/scss/modules/font-sizes.module.scss, es-bs-base/scss/modules/font-weights.module.scss, es-bs-base/scss/modules/heading-eyebrow.module.scss, es-bs-base/scss/modules/heading-font-sizes-desktop.module.scss, es-bs-base/scss/modules/heading-font-sizes-mobile.module.scss, es-bs-base/scss/modules/heading-general.module.scss, es-bs-base/scss/modules/heading-line-heights-desktop.module.scss, es-bs-base/scss/modules/heading-line-heights-mobile.module.scss, es-bs-base/scss/modules/line-heights.module.scss, es-bs-base/scss/modules/post-font-sizes-desktop.module.scss, es-bs-base/scss/modules/post-font-sizes-mobile.module.scss, es-bs-base/scss/modules/post-general.module.scss, es-bs-base/scss/modules/post-line-heights-desktop.module.scss, es-bs-base/scss/modules/post-line-heights-mobile.module.scss, es-bs-base/scss/modules/type.module.scss, es-ds-docs/pages/atoms/typography.vue
- https://energysage.atlassian.net/browse/CED-1736
- Created typography atom for es-ds 3.0
- Created 15 SCSS modules used in typography
- Followed example of atom color.vue for Prism code
- Tested locally on http://localhost:8500/atoms/typography
- Overall
=> feat: typography atom for es-ds 3.0

es-ds-components/components/es-progress-circle.vue, es-ds-docs/components/ds-molecules-list.vue, es-ds-docs/pages/molecules/data-table-simple.vue, es-ds-docs/pages/molecules/progress-circle.vue, es-ds-docs/pages/molecules/progress.vue, es-ds-docs/pages/molecules/radio-button.vue
- https://energysage.atlassian.net/browse/CED-1751
- Created progress-circle molecule for es-ds 3.0
- Created es-progress-circle component based on es-ds 2.0
- Added progress circle link to ds-molecules-list.vue
- Tested the changes on http://localhost:8500/molecules/progress-circle
- I am waiting on approval of [CED-1739](https://energysage.atlassian.net/browse/CED-1739) to incorporate es-button.
[CED-1739]: https://energysage.atlassian.net/browse/CED-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: progress circle molecule for es-ds 3.0

es-ds-components/components/es-rating.vue, es-ds-docs/components/ds-molecules-list.vue, es-ds-docs/pages/molecules/rating.vue
[CED-1752: Create v3 EsRating using PrimeVue](https://energysage.atlassian.net/browse/CED-1752)
- Created rating molecule for es-ds 3.0
- Created es-rating component
- create a wrapper around PrimeVue DataTable
- use pass through to fix style issues
-  Added rating link to ds-molecules-list.vue
- TODO:
- tabs "Moves focus to the star representing the value, if there is none then first star receives the focus."
- Tested locally on http://localhost:8500/molecules/rating
- What is the best implementation for half stars?
[CED-1752]: https://energysage.atlassian.net/browse/CED-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: EsRating molecule for es-ds 3.0 

es-ds-components/.gitignore, es-ds-components/components/es-button.vue, es-ds-components/components/es-spinner.vue, es-ds-docs/components/ds-molecules-list.vue, es-ds-docs/pages/molecules/button.vue
https://energysage.atlassian.net/browse/CED-1739
- Add `es-button` to `es-ds-components`
- Added button page for documentation
Manual comparison with current styles
- There's a loading prop in prime-vue that `disables` the button when `true`, this seems like behavior we may want to consider
=> feat: es v3 button

.vscode/extensions.json
- https://energysage.atlassian.net/browse/CED-1819
- Lets make sure we only suggest vscode extensions that work well with vue3/nuxt3
- I just limited the suggestions and made sure to use the right vue extension
- All extensions suggested I'm using locally
- 🤷
=> CED-1819 update vscode extensions

es-ds-docs/package-lock.json, es-ds-docs/package.json, es-ds-docs/patches/prismjs+1.29.0.patch
https://energysage.atlassian.net/browse/CED-1824
- Applied patch from https://github.com/PrismJS/prism/pull/3672 using https://www.npmjs.com/package/patch-package
- Ran `make dev` and saw the error went away
-
=> CED-1824 Fix warning about color-adjust in the Vue 3 design system

es-ds-docs/pages/molecules/accordion.vue, es-ds-docs/pages/molecules/collapse.vue, es-ds-docs/pages/molecules/form-input.vue, es-ds-docs/pages/molecules/form-msg.vue, es-ds-docs/pages/molecules/progress-circle.vue, es-ds-docs/pages/molecules/progress.vue, es-ds-docs/pages/molecules/rating.vue
- https://energysage.atlassian.net/browse/CED-1817
- Switched from `<button>` to EsButton on Accordion, Form input, Form message, Progress, and Progress circle docs pages
- Switched from `<input>` checkbox to EsFormCheckbox on Collapse docs page
- Fixed a typo on the Rating docs page
- Overall
=> fix: update docs pages to use EsButton and EsFormCheckbox

es-ds-components/components/es-modal.vue, es-ds-docs/pages/molecules/modal.vue, es-ds-styles/scss/vue/components/_modal.scss
- https://energysage.atlassian.net/browse/CED-1832
- Added open and close animation to modal that mirrors the nice one from PrimeVue
- Added animation for the modal mask (backdrop)
- Made animation only happen if the user hasn't set a "reduce motion" preference
- Tested locally, with macOS accessibility setting "Reduce motion" on and off (had to restart Chrome)
- Overall
=> feat: added animation to modal

README.md, es-ds-docs/aws/README.md, es-ds-docs/aws/bin/aws.js, es-ds-docs/aws/cdk.context.json, es-ds-docs/aws/cdk.json, es-ds-docs/aws/lib/stack-static.js, es-ds-docs/aws/package-lock.json, es-ds-docs/aws/package.json, es-ds-docs/pages/atoms/spacing.vue
https://energysage.atlassian.net/browse/CED-1729
- Copy in the AWS folder from the old design system docs. Verified that the CDK deploy works fine.
- Created a [Confluence doc](https://energysage.atlassian.net/wiki/spaces/CE/pages/1094058044/3.0+and+later+Deploy+Design+System+Documentation) on the deploy process which is now linked from the README. The process is the same except for some different npm commands in the new version
- Fixed a minor issue in the `spacing.vue` docs which causes a warning to be thrown during static generation
- Verified that the CDK deploy works
- General
=> CED-1729: aws deploy

es-ds-components/components/es-accordion-list.vue, es-ds-styles/scss/_card.scss, es-ds-styles/scss/_transitions.scss, es-ds-styles/scss/vue/components/_accordion.scss, es-ds-styles/scss/vue/components/_tabs.scss
- https://energysage.atlassian.net/browse/CED-1840
- Wrapped the appropriate transition attributes for Accordion, Card, Collapse, and Tabs in a media query so when "reduce motion" is on, they won't animate
- The accordion actually already had some of these in place but the syntax was wrong (no parentheses) so it wasn't working
- Tested locally, with macOS accessibility setting "Reduce motion" on and off (had to restart Chrome)
- Tested other components like Checkbox and Radio button and Progress but they already work with this setting because they're leveraging the Bootstrap `transition.$transition()` function - which is sort of overcomplicated and unnecessary for us to use on new things
- Overall
=> feat: implement reduced motion mode for accordion, card, collapse, tabs

.github/workflows/ci.yml, es-ds-components/components/es-popover.vue, es-ds-docs/.eslintrc.json, es-ds-docs/components/ds-molecules-list.vue, es-ds-docs/pages/atoms/typography.vue, es-ds-docs/pages/molecules/file-input.vue, es-ds-docs/pages/molecules/popover.vue
N/A, this is a 0-pointer
For whatever reason, eslint was not actually being run on Vue files. This PR updates the eslint config to address this. It also disables eslint rules that conflict with prettier, and addresses a scattering of linting problems that were previously missed.
Made sure the dev server and static generation still works. Made sure linting passes, and that introducing violations actually causes a failure. Checking PR CI.
- General
=> Actually apply eslint to vue

es-ds-components/nuxt.config.ts, es-ds-docs/package-lock.json, es-ds-docs/package.json
`html-truncate` causing [build error](https://github.com/EnergySage/es-ds/actions/runs/10800664124/job/29959174593).  Importing in `es-ds-docs` as well as components & adding to optimizeDeps config.
-
=> Fix: import breaking full build

es-ds-components/components/es-support-card.vue, es-ds-docs/components/ds-organisms-list.vue, es-ds-docs/components/ds-prop-table.vue, es-ds-docs/pages/organisms/support-card.vue
https://energysage.atlassian.net/browse/CED-1786
Create EsSupportCard with the [same props API](https://design.energysage.dev/organisms/es-support-card/) for backwards compatibility. Docs page uses `fullWidthComponent` layout instead of default, and the props and slots tables now use `ds-prop-table`.
Tested locally on http://localhost:8500/organisms/support-card
- General
=> feat: v3 EsSupportCard

es-ds-components/components/es-rating.vue, es-ds-docs/pages/molecules/rating.vue
https://energysage.atlassian.net/browse/CED-1822
This PR adds onto work done in a [previous PR](https://github.com/EnergySage/es-ds/pull/1490) to add EsRating v3 molecule. Remaining items included:
- Create half star functionality for read only ratings
- Done by not using PrimeVue's rating component for read only ratings
- Fix accessibility label for half stars defaulting to 1
- Done by adding aria attributes
- tabs "Moves focus to the star representing the value, if there is none then first star receives the focus."
- Done applying focus style to `focused` property
Tested locally on http://localhost:8500/molecules/rating
- Remaining issues
- change event is triggering twice
- focus state is persisting on click - star stays zoomed
=> feat: finish EsRating TODOs

es-ds-docs/pages/molecules/checkbox.vue
https://energysage.atlassian.net/browse/CED-1825
- Added proper event handler to all checkboxes on the Checkbox page so that the Select All state will get updated correctly when any of them are checked or unchecked
- Tested locally on the Checkbox docs page
- Overall
=> fix: correct logic gaps in Select All functionality on Checkbox page

es-ds-components/components/es-cta-card.vue, es-ds-docs/components/ds-organisms-list.vue, es-ds-docs/pages/organisms/cta-card.vue
https://energysage.atlassian.net/browse/CED-1783
- Added EsCtaCard and its associated docs page
- Tested locally on CTA card docs page
- Overall
=> feat: added EsCtaCard and docs page

es-ds-docs/components/ds-molecules-list.vue, es-ds-docs/pages/atoms/corners.vue, es-ds-docs/pages/molecules/textarea.vue
- https://energysage.atlassian.net/browse/CED-1774
- Fixed the links to Popover, Textarea, and Verification code on the Corners page
- Corrected the URL slug of the Textarea page from `form-textarea` to `textarea` to be consistent with the other pages and with the friendly name displayed in the navigation
- Tested locally by going to Corners page and clicking each link
- Overall
=> fix: component links from Corners page, made textarea URL slug consistent with other pages

es-ds-components/components/es-cta-banner.vue, es-ds-docs/components/ds-organisms-list.vue, es-ds-docs/pages/organisms/cta-banner.vue
[CED-1782: Create v3 EsCtaBanner](https://energysage.atlassian.net/browse/CED-1782)
- Created v3 `EsCtaBanner` component in new Design System feature branch
- Created new docs page
- Changed `b-row` and `b-col` references to `es-row` and `es-col`
- Converted script to Composition API
- Tested locally at http://localhost:8500/organisms/cta-banner
- Compared results to previous version of component at https://design.energysage.dev/organisms/es-cta-banner/
=> CED-1782: v3 EsCtaBanner

es-ds-styles/scss/_variables.scss
- https://energysage.atlassian.net/browse/CED-1894
- Getting an error downstream about using the deprecated `fade-in` SASS function
- Error goes away downstream when the change is made 
-
=> feat: fix deprecated function

es-ds-components/utils/get-es-nav-bar-global-content.js
https://energysage.atlassian.net/browse/CED-1908
- Update links in product nav menu
- In the “Home solar” product nav menu, change the URL destination of the “Financing” link
- In the “Home solar” product nav menu, insert a new link under the “Financing” link
- In the “Heating & cooling” product nav menu, insert a new link after the “Heat pump incentives” link
- New image for Editors' Pick comes from es-site
Tested locally at http://localhost:8500/organisms/nav-bar
- General
=> feat: update links in nav bar

es-ds-components/components/es-col.vue, es-ds-components/package-lock.json, es-ds-docs/pages/atoms/layout.vue
https://energysage.atlassian.net/browse/CED-1894
- The `<es-col>` implementation was improperly adding the `col` class to all of its instances, even when breakpoints are specified, which resulted in layout bugs downstream. When we have `<es-col md="6">`, we want only `<div class="col-md-6">`, not `<div class="col col-md-6">`.
- Improved documentation
Manual testing on the broken instance in in-progress branch of es-cms-pages
- general
=> fix: layout issues on b-col

es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json, es-ds-styles/package-lock.json, es-ds-styles/package.json
=> chore: update package versions for alpha release

es-ds-components/components/es-data-table-column.vue, es-ds-components/components/es-data-table.vue, es-ds-docs/pages/molecules/data-table.vue
- https://energysage.atlassian.net/browse/CED-2000
- Makes it possible to customize the contents of an EsDataTable cell with a template
- Moves away from the Bootstrap Vue table API towards the PrimeVue DataTable / Column API
- Performed an audit of data table usage in Storyblok prod; made the examples more real world (and less engineering specific, since we had a props table as our example before) to better demonstrate what data tables will actually be used for
- Unable to test with es-storyblok-shared and RichDataTable on es-cms-pages and LandingDataTable due to EBADF and "EMFILE: too many open file" errors
- Overall
=> feat: enable templated EsDataTable cells; better match PrimeVue API

es-ds-components/components/icon/ccpa-opt-out.vue, es-ds-components/utils/get-es-footer-content.ts
https://energysage.atlassian.net/browse/CED-2153
Comment out the privacy link in `legalLinks` in the Footer content; this is the simplest way to take it out for now while leaving the changes ready to go
Run locally on http://localhost:8500/organisms/footer
-
=> fix: comment out privacy choices link in footer

es-ds-components/components/es-video.vue
- https://energysage.atlassian.net/browse/CED-2163
- Updates the `<iframe>` embed code for EsVideo to the new code provided by YouTube's embed sharing feature - I'm optimistic that the new `allow` attribute that mentions `picture-in-picture` may help prevent the "[Violation] Permissions policy violation: picture-in-picture is not allowed in this document.” error we've occasionally been seeing in the console when the video doesn't play
- Will have to fully test downstream with a release
- Tested locally and on the docs site, videos still play, so definitely doesn't seem to do any harm
- Overall
=> fix: update youtube embed code with new attributes

es-ds-components/components/es-zip-code-form.vue, package-lock.json
https://energysage.atlassian.net/jira/software/c/projects/CED/boards/76/backlog?selectedIssue=CED-2115&text=etelson%20alciu
A package-lock.json was generated from my last merge, this PR contains its removal and also the addition of "mb-100" which was removed during the process of my CSS overwrite code changes to es-zip-code-form. [See this PR for context.
](https://github.com/EnergySage/es-ds/pull/1573)
Tested following es-ds instructions:
https://github.com/EnergySage/es-ds
- general
=> refactor: mb-100 added back, package-lock.json file that was generated is removed

es-ds-components/components/es-collapse.vue
- https://energysage.atlassian.net/browse/CED-2173
- The EsCollapse expand/collapse button now has a descriptive label that will be read out upon navigating to it via screen reader
- Tested with VoiceOver
- Overall
=> fix: add descriptive text to EsCollapse expand/collapse button

.github/PULL_REQUEST_TEMPLATE.md
- n/a
- I noticed the PR description template references Storyblok, which doesn't make sense in the design system. This PR removes that line.
- n/a
- Overall
=> docs: remove PR template line referencing Storyblok

es-ds-components/components/es-cta-banner.vue, es-ds-docs/pages/organisms/cta-banner.vue
- https://energysage.atlassian.net/browse/CED-2264
- Added a new variant to EsCtaBanner: `stacked`
- Added a new `background` prop to EsCtaBanner (three values: `none`, `blue-300-radial`, or `dark-blue`)
- Deprecated the `dark` prop in EsCtaBanner (but added an example that uses it to show it still works for now)
- Tested locally on http://localhost:8500/organisms/cta-banner
- Overall
=> feat: EsCtaBanner now accepts a background prop and a stacked variant

CHANGELOG.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json
=> chore: release 3.0.10

es-ds-components/components/es-video.vue
https://energysage.atlassian.net/browse/CORE-6393
The video https://www.youtube.com/embed/bx_rneY1OS4?wmode=opaque fails to load on quote frontend because it contains a `_` that is not allowed in current regular expression.
Tested with quote-frontend.
-
=> fix: youtube video regular expression should contain _

CHANGELOG.md, README.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json, es-ds-styles/package-lock.json, es-ds-styles/package.json
=> chore: release 3.1.0

es-ds-components/components/icon/twitter.vue
Part of https://energysage.atlassian.net/browse/CED-2298
- fixing a tiny bug where part of the twitter icon svg was set to white fill
Icons page, or by linking to CED-2298 branch in es-cms-pages
-
=> fix: color on part of twitter icon

CHANGELOG.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json
=> chore: release 3.1.1

CHANGELOG.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json, es-ds-styles/package-lock.json, es-ds-styles/package.json
=> chore: release 3.1.3

es-ds-docs/package-lock.json, es-ds-docs/package.json
=> fix: update deps for es-ds-styles 3.1.3 publish

CHANGELOG.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json
=> chore: release 3.1.4

es-ds-components/components/es-cta-banner.vue, es-ds-components/package-lock.json, es-ds-docs/components/ds-sample-email-form.vue, es-ds-docs/pages/organisms/cta-banner.vue
- https://energysage.atlassian.net/browse/CED-2306
- Adds a new `sideImage` slot to EsCtaBanner
- Adds new `sideImageContainerClass` prop to EsCtaBanner
- Adds new `semi-wide` option to the `variant` prop of EsCtaBanner
- New/updated examples on the EsCtaBanner page
- Tested locally on http://localhost:8500/organisms/cta-banner
- Also tested by linking es-cms-articles (https://github.com/EnergySage/es-cms-articles/pull/626) and storyblok-shared (https://github.com/EnergySage/es-storyblok-shared/pull/402) and going to https://localhost:8720/news/how-new-trump-tariffs-could-affect-the-solar-industry/
- Overall
=> feat: added side image and semi-wide variant to EsCtaBanner

CHANGELOG.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json
=> chore: release 3.1.5

es-ds-docs/components/ds-examples-list.vue, es-ds-docs/nuxt.config.ts, es-ds-docs/package-lock.json, es-ds-docs/package.json, es-ds-docs/pages/examples/reordering-with-motion.vue
- n/a
- Inspired by the prototype showed in product review this morning, I added a new example page called "Reordering with motion" to show an easy way that type of list reordering animation could be accomplished (hopefully the first of many motion integrations into our UI/UX)
- Intentionally didn't saddle es-ds-components with this extra library, only es-ds-docs - teams can choose whether or not to use it, this just shows one easy example of how to do so
- Overall
=> feat: added example of animating a list reorder using Motion for Vue

.github/workflows/deploy-v3.yml
- https://energysage.atlassian.net/browse/CED-2329
- Switches from a custom IAM role to the standard OIDC role as per Platform's instructions
- Confirmed the DefaultDevDeployRole exists within the es-ds-dev AWS account
- Roughly confirmed the DefaultDevDeployRole should have the same S3 write and CodeArtifact read permissions that the custom "github-write-to-s3" role has, so this should probably work
- I believe the only way to test is to merge this into main and see if the automatic deploy job that gets kicked off works
- Overall
=> fix: switch AWS login from IAM to OIDC

.github/workflows/deploy.yml
- https://energysage.atlassian.net/browse/CED-2143
- Fix issue where needed workflow inputs weren't present when deploy workflow was triggered by push to main
- Need to merge to main to test
- Overall
=> fix: default inputs when deploy not triggered manually

.github/workflows/build.yml
- https://energysage.atlassian.net/browse/CED-2143
- Uncomment the "cdk diff" step in build.yml now that the stack exists
- Tested successfully via [branch deploy to int](https://github.com/EnergySage/es-ds/actions/runs/15400877363)
- Overall
=> fix: uncomment cdk diff step now that the stack exists

es-ds-components/components/es-progress.vue, es-ds-components/utils/omit.ts, es-ds-docs/pages/molecules/progress.vue, es-ds-styles/scss/_progress.scss, es-ds-styles/scss/_variables.scss
- https://energysage.atlassian.net/browse/CED-2478
- Brings EsProgress into alignment with the updated Figma designs that have been out for many months
- Added `formatter`, `showCircle`, and `valueClass` props
- This is a breaking change as all instances of EsProgress, especially those with custom styles applied, will need to be reviewed and adjusted for visual consistency (likely those custom styles can be removed, in cases where they were applied to match the design)
- Tested locally - and did a quick [code search](https://github.com/search?q=org%3AEnergySage%20es-progress&type=code) to see how it's being used
- Overall
=> feat: match EsProgress to design

CHANGELOG.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json, es-ds-styles/package-lock.json, es-ds-styles/package.json
=> chore: release 3.2.0

CLAUDE.md
- n/a
- Added CLAUDE.md for all to use, and to save on costs regenerating it each time
- n/a
- Overall
=> docs: add CLAUDE.md

CHANGELOG.md, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json, es-ds-styles/package-lock.json, es-ds-styles/package.json
=> chore: release 3.2.1

CHANGELOG.md, es-ds-components/components/es-progress.vue, es-ds-components/package-lock.json, es-ds-components/package.json, es-ds-docs/package-lock.json, es-ds-docs/package.json
- https://energysage.atlassian.net/browse/CED-2478
- Import `omit` utility function from `#imports` explicitly to avoid `Property 'omit' does not exist on type 'CreateComponentPublicInstanceWithMixins` type error in downstream repos running TypeScript
- (created [CED-2489](https://energysage.atlassian.net/browse/CED-2489) to help catch this earlier in the future)
- First reproduced the type error locally in a downstream repo by npm linking to es-ds-components
- Then confirmed the fix the same way
- Overall
[CED-2489]: https://energysage.atlassian.net/browse/CED-2489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: type error with EsProgress in downstream repos running TypeScript

.github/workflows/ci.yml, .github/workflows/release-please.yml, es-ds-components/.prettierignore
- Exempt changelogs from prettier
- Include CI in the release process
=> fix: various build and release issues

es-ds-components/components/es-data-table.vue, es-ds-docs/pages/molecules/data-table.vue
https://energysage.atlassian.net/browse/INS-3548
- In `es-data-table.vue`: Added a named slot template that passes through to the PrimeVue DataTable component's empty slot.
- In `data-table.vue` docs: Added an example showing how to use the empty slot when the items array is empty
- Tested locally 
- Overall
=> feat: INS-3548 Add new empty template slot to es data table

es-ds-components/components/es-dropdown-select.vue, es-ds-components/nuxt.config.ts, es-ds-docs/pages/molecules/dropdown-select.vue
In order to get just the value from the selected option in the dropdown, add `optionValue` prop to `dropdown` that is defined as `value` when the options prop is an array of objects. Also add `v-bind="$attrs"` in case there is a need to pass other props in the future.
Tested on http://localhost:8500/molecules/dropdown-select
- Non-object examples still work as expected
- Object example returns the value without needing to extract with `.value`
- General
=> fix: define value for dropdown option

es-ds-docs/package-lock.json
https://energysage.atlassian.net/browse/CED-2580
Manual release by running `npm install @energysage/es-ds-components@3.7.1`
-
=> chore: manual release 3.7.1
